import PDFDocument from "pdfkit";
import type { AiceDecisionObject, ReportSnapshot, VisualState } from "@systolab/shared";
import { VISUAL_STATES } from "@systolab/shared";

export async function renderCustomerDecisionPdf(decision: AiceDecisionObject): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 44, size: "A4", bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("error", reject);
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    writeCustomerDecisionHeader(doc, decision);
    writeCustomerDecisionBoundary(doc, decision);
    writeCustomerEvidenceSummary(doc, decision);
    writeCustomerBusinessBoundary(doc, decision);
    writeCustomerRecommendation(doc, decision);
    writeCustomerDecisionFooter(doc);
    doc.end();
  });
}

function writeCustomerDecisionHeader(doc: PDFKit.PDFDocument, decision: AiceDecisionObject): void {
  doc
    .fillColor("#17201d")
    .fontSize(22)
    .text("SYSTOLAB Customer Decision Report")
    .fontSize(10)
    .fillColor("#52605a")
    .text(`Target: ${decision.target}`)
    .text("Customer Intelligence Plane")
    .moveDown(1);

  doc
    .fontSize(24)
    .fillColor(decision.confidence_score >= 75 ? "#16845b" : decision.confidence_score >= 45 ? "#b87500" : "#b3261e")
    .text(`${decision.confidence_score}% Confidence`)
    .fontSize(10)
    .fillColor("#17201d")
    .text(`Risk level: ${toPdfTitleCase(decision.risk_level)}`)
    .text(`Coverage: ${decision.coverage_score}% ${decision.evidence_summary.coverage_status}`)
    .moveDown(0.8);
}

function writeCustomerDecisionBoundary(doc: PDFKit.PDFDocument, decision: AiceDecisionObject): void {
  sectionTitle(doc, "Assessment Boundary");
  doc
    .fontSize(9)
    .fillColor("#17201d")
    .text(`Access Restriction Detected: ${decision.access_restriction_detected ? "Yes" : "No"}`)
    .fillColor("#52605a")
    .text(decision.assessment_limitation || "Assessment was limited to validated evidence collected during this scan.")
    .moveDown(0.8);
}

function writeCustomerEvidenceSummary(doc: PDFKit.PDFDocument, decision: AiceDecisionObject): void {
  sectionTitle(doc, "Evidence Summary");
  doc
    .fontSize(9)
    .fillColor("#17201d")
    .text(decision.evidence_summary.overview)
    .fillColor("#52605a")
    .text(`Sampled pages: ${decision.evidence_summary.sampled_pages}`)
    .text(`Strongest signal: ${decision.evidence_summary.strongest_business_signal}`)
    .text(`Weakest signal: ${decision.evidence_summary.weakest_business_signal}`)
    .moveDown(0.6);

  for (const item of decision.evidence_heatmap_summary) {
    doc
      .fontSize(8)
      .fillColor("#17201d")
      .text(`${item.area}: ${toPdfTitleCase(item.coverage)}`)
      .fillColor("#52605a")
      .text(item.business_meaning)
      .moveDown(0.25);
  }
  doc.moveDown(0.4);
}

function writeCustomerBusinessBoundary(doc: PDFKit.PDFDocument, decision: AiceDecisionObject): void {
  sectionTitle(doc, "Business Impact Boundary");
  doc
    .fontSize(9)
    .fillColor("#17201d")
    .text(`Impact: ${decision.impact}`)
    .text(`Opportunity range: ${formatPdfDecisionRange(decision.revenue_impact_range)}`)
    .text(`Time sensitivity: ${decision.time_sensitivity}`)
    .text(`Action window: ${decision.recommended_action_window}`)
    .fillColor("#52605a")
    .text(decision.if_not_fixed_outcome)
    .moveDown(0.8);
}

function writeCustomerRecommendation(doc: PDFKit.PDFDocument, decision: AiceDecisionObject): void {
  sectionTitle(doc, "Recommended Action");
  doc.fontSize(10).fillColor("#17201d").text(decision.final_recommendation).moveDown(1);
}

function writeCustomerDecisionFooter(doc: PDFKit.PDFDocument): void {
  const pages = doc.bufferedPageRange();
  for (let index = 0; index < pages.count; index += 1) {
    doc.switchToPage(index);
    doc
      .fontSize(8)
      .fillColor("#7b8580")
      .text("Generated by SYSTOLAB Intelligence Platform. Conclusions are limited to validated evidence collected during the current scan.", 44, doc.page.height - 42, {
        align: "center"
      });
  }
}

function toPdfTitleCase(value: string): string {
  return value
    .toLowerCase()
    .replaceAll("_", " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function formatPdfDecisionRange(range: AiceDecisionObject["revenue_impact_range"]): string {
  if (range.low === 0 && range.high === 0) return range.label;
  const formatter = new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 });
  return `${range.label}: ${formatter.format(range.low)}-${formatter.format(range.high)} ${range.unit.replaceAll("_", " ")}`;
}

export async function renderReportPdf(
  report: ReportSnapshot,
  getArtifact?: (artifactId: string) => Promise<Buffer | null>
): Promise<Buffer> {
  validatePdfIntegrity(report, "customer");
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 54, size: "A4", bufferPages: true, compress: false });
    doc.info.Title = "SYSTOLAB Revenue Health Diagnosis";
    doc.info.Subject = "Generated by SYSTOLAB Intelligence Platform.";
    doc.info.Keywords =
      "SYSTOLAB Decision Intelligence Brief, Full Customer Intelligence Report, Revenue Intelligence Engine, Recommendation Outcome Validation Loop, Evidence Database, executive report, revenue health diagnosis";
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("error", reject);

    doc.on("end", () => resolve(Buffer.concat(chunks)));

    const finish = async () => {
      try {
        writeEnterpriseReportHeader(doc, report);
        writeEnterpriseDecisionBrief(doc, report);
        writeEnterpriseScoreOverview(doc, report);
        writeEnterpriseRecommendedActions(doc, report);
        writeEnterprisePriorityTimeline(doc, report);
        writeEnterpriseEvidenceBoundary(doc, report);
        writeEnterpriseFreshness(doc, report);
        await writeCustomerFullReportSections(doc, report, getArtifact);
        writeEnterpriseFooterAndPageNumbers(doc);
        doc.end();
      } catch (error) {
        reject(error);
      }
    };

    void finish();
    return;
    const afterSync = () => undefined;

    writeEnterpriseReportHeader(doc, report);
    writeEnterpriseDecisionBrief(doc, report);
    writeEnterpriseScoreOverview(doc, report);
    writeEnterpriseRecommendedActions(doc, report);
    writeEnterprisePriorityTimeline(doc, report);
    writeEnterpriseEvidenceBoundary(doc, report);
    writeEnterpriseFreshness(doc, report);
    writeEnterpriseFooterAndPageNumbers(doc);
    doc.end();
    return;

    writeHeader(doc, report);
    writeDecisionIntelligenceBrief(doc, report);
    writeActionFirst(doc, report);
    writeSystemVerdict(doc, report);
    writeOssInterpretation(doc, report);
    writeVerdict(doc, report);
    writeBusinessRisk(doc, report);
    writeEvidenceCoverage(doc, report);
    writeFreshness(doc, report);
    writeVitalSigns(doc, report);
    writeExecutiveTable(doc, report);
    writeOutcomeBridge(doc, report);
    writeRevenueIntelligence(doc, report);
    writeRecommendationEngine(doc, report);
    writeOutcomeValidation(doc, report);
    writeConfidenceEngine(doc, report);
    writeIndustryBenchmark(doc, report);
    writePriorityTimeline(doc, report);
    writeTransformation(doc, report);
    writeChangeDetection(doc, report);
    writeClosedLoop(doc, report);
    writeMarketReadiness(doc, report);
    writeGbpIdentity(doc, report);
    writeCompetitorComparison(doc, report);
    writeCompetitorIntelligence(doc, report);
    writeDimensions(doc, report);
    writeDecisions(doc, report);
    writeGroundTruthLog(doc, report);
    writeEvidenceDatabase(doc, report);
    writeMonitoringAlerts(doc, report);
    writeMemoryEvolution(doc, report);
    writeSystemHealth(doc, report);
    writeEvidenceExplorer(doc, report);

    // Async section — screenshot embeds — then finalize
    void afterSync();
  });
}

export async function renderInternalReportPdf(
  report: ReportSnapshot,
  getArtifact?: (artifactId: string) => Promise<Buffer | null>
): Promise<Buffer> {
  validatePdfIntegrity(report, "internal");
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 54, size: "A4", bufferPages: true, compress: false });
    doc.info.Title = "SYSTOLAB Internal Intelligence Report";
    doc.info.Subject = "INTERNAL INTELLIGENCE REPORT - CONFIDENTIAL";
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("error", reject);
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    const finish = async () => {
      try {
        doc
          .font("Helvetica-Bold")
          .fontSize(15)
          .fillColor(ENTERPRISE_PDF.red)
          .text("INTERNAL INTELLIGENCE REPORT - CONFIDENTIAL")
          .moveDown(0.4);
        writeHeader(doc, report);
        writeDecisionIntelligenceBrief(doc, report);
        writeActionFirst(doc, report);
        writeSystemVerdict(doc, report);
        writeOssInterpretation(doc, report);
        writeVerdict(doc, report);
        writeBusinessRisk(doc, report);
        writeEvidenceCoverage(doc, report);
        writeFreshness(doc, report);
        writeVitalSigns(doc, report);
        writeExecutiveTable(doc, report);
        writeOutcomeBridge(doc, report);
        writeRevenueIntelligence(doc, report);
        writeRecommendationEngine(doc, report);
        writeOutcomeValidation(doc, report);
        writeConfidenceEngine(doc, report);
        writeIndustryBenchmark(doc, report);
        writePriorityTimeline(doc, report);
        writeTransformation(doc, report);
        writeChangeDetection(doc, report);
        writeClosedLoop(doc, report);
        writeMarketReadiness(doc, report);
        writeGbpIdentity(doc, report);
        writeCompetitorComparison(doc, report);
        writeCompetitorIntelligence(doc, report);
        writeDimensions(doc, report);
        writeDecisions(doc, report);
        writeGroundTruthLog(doc, report);
        writeEvidenceDatabase(doc, report);
        writeMonitoringAlerts(doc, report);
        writeMemoryEvolution(doc, report);
        writeSystemHealth(doc, report);
        writeEvidenceExplorer(doc, report);
        await writeScreenshotEvidence(doc, report, getArtifact);
        writeArchitectureState(doc, report);
        writeVisualFramework(doc);
        writeInternalFooterAndPageNumbers(doc);
        doc.end();
      } catch (error) {
        reject(error);
      }
    };

    void finish();
  });
}

async function writeCustomerFullReportSections(
  doc: PDFKit.PDFDocument,
  report: ReportSnapshot,
  getArtifact?: (artifactId: string) => Promise<Buffer | null>
): Promise<void> {
  doc.addPage();
  writeEnterpriseContinuationHeader(doc);
  writeEnterpriseSectionLabel(doc, report, "Full Customer Intelligence Report");
  writeEnterpriseBox(doc, report, "Included Customer Report Sections", "blue", 210, () => {
    const sections = [
      "Decision Intelligence Brief",
      "Action First Panel",
      "System Verdict",
      "OSS Score Interpretation",
      "3-Second Executive Clarity",
      "Business Risk Status",
      "Evidence Coverage Summary",
      "Data Freshness & Validity Window",
      "Business Vital Signs",
      "Executive Summary",
      "Business Outcome Bridge",
      "Revenue Intelligence Engine",
      "Recommendation Engine",
      "Recommendation Outcome Validation Loop",
      "Confidence Engine",
      "Industry Benchmark Engine",
      "Priority Timeline Framework",
      "Transformation Intelligence Layer",
      "Lightweight Change Detection",
      "Closed-Loop Proof System",
      "Market Readiness Position",
      "GBP Identity Intelligence",
      "Client vs Competitor Structural Comparison",
      "Competitor Intelligence Engine",
      "Operational Dimension Scores",
      "System Decision Summary",
      "Evidence Database",
      "Monitoring Scheduler & Alert Engine",
      "Memory, Evolution, Threat, DNA, and Edit Intelligence",
      "Screenshot Evidence",
      "SYSTOLAB Visual Intelligence Framework"
    ];
    const x = enterpriseInnerX(doc);
    const width = enterpriseInnerWidth(doc);
    const columns = 2;
    const columnWidth = (width - 16) / columns;
    const startY = doc.y;
    sections.forEach((section, index) => {
      const col = index % columns;
      const row = Math.floor(index / columns);
      doc
        .font("Helvetica")
        .fontSize(8.5)
        .fillColor(ENTERPRISE_PDF.ink)
        .text(`${index + 1}. ${section}`, x + col * (columnWidth + 16), startY + row * 16, { width: columnWidth });
    });
    doc.y = startY + Math.ceil(sections.length / columns) * 16;
  });

  doc.addPage();
  writeEnterpriseContinuationHeader(doc);
  writeDecisionIntelligenceBrief(doc, report);
  writeActionFirst(doc, report);
  writeSystemVerdict(doc, report);
  writeOssInterpretation(doc, report);
  writeVerdict(doc, report);
  writeBusinessRisk(doc, report);
  writeEvidenceCoverage(doc, report);
  writeFreshness(doc, report);
  writeVitalSigns(doc, report);
  writeExecutiveTable(doc, report);
  writeOutcomeBridge(doc, report);
  writeRevenueIntelligence(doc, report);
  writeRecommendationEngine(doc, report);
  writeOutcomeValidation(doc, report);
  writeConfidenceEngine(doc, report);
  writeIndustryBenchmark(doc, report);
  writePriorityTimeline(doc, report);
  writeTransformation(doc, report);
  writeChangeDetection(doc, report);
  writeClosedLoop(doc, report);
  writeMarketReadiness(doc, report);
  writeGbpIdentity(doc, report);
  writeCompetitorComparison(doc, report);
  writeCompetitorIntelligence(doc, report);
  writeDimensions(doc, report);
  writeDecisions(doc, report);
  writeEvidenceDatabase(doc, report);
  writeMonitoringAlerts(doc, report);
  writeMemoryEvolution(doc, report);
  await writeCustomerScreenshotEvidence(doc, report, getArtifact);
  writeVisualFramework(doc);
}

type PdfReportMode = "customer" | "internal";

const CUSTOMER_PDF_FORBIDDEN_PATTERN =
  /crawler|parser|executionProvenance|rawSignalTelemetry|validationTrace|systemHealthState|execution trace|trace id|http trace|dom trace|recovery log|bot-detection|challenge type|compatibility intelligence|failure memory|rendering diagnostics|operational diagnostics|system health|evidence explorer|ground truth validation|layered intelligence architecture/i;

function validatePdfIntegrity(report: ReportSnapshot, mode: PdfReportMode): void {
  const brief = pdfDecisionBrief(report);
  const missing: string[] = [];
  const requireValue = (label: string, value: unknown) => {
    if (value === undefined || value === null || value === "") missing.push(label);
  };

  requireValue("snapshotId", report.snapshotId);
  requireValue("targetUrl", report.targetUrl);
  requireValue("createdAt", report.createdAt);
  requireValue("scanCoverage.coverageLabel", report.scanCoverage?.coverageLabel);
  requireValue("decisionIntelligenceBrief.executiveVerdict.currentSituation", brief.executiveVerdict.currentSituation);
  requireValue("decisionIntelligenceBrief.executiveActionBanner.classification", brief.executiveActionBanner.classification);
  requireValue("decisionIntelligenceBrief.executiveDecisionMatrix.riskLevel", brief.executiveDecisionMatrix.riskLevel);
  requireValue("decisionIntelligenceBrief.executiveDecisionMatrix.recommendedNextAction", brief.executiveDecisionMatrix.recommendedNextAction);
  requireValue("decisionIntelligenceBrief.executiveReliabilityPanel.overallReportReliability", brief.executiveReliabilityPanel.overallReportReliability);

  if (missing.length > 0) {
    throw new Error(`PDF integrity validation failed: missing required customer fields: ${missing.join(", ")}`);
  }

  if (mode === "customer") {
    const customerRenderPayload = {
      snapshotId: report.snapshotId,
      targetUrl: report.targetUrl,
      createdAt: report.createdAt,
      scanCoverage: report.scanCoverage?.coverageLabel,
      decisionIntelligenceBrief: brief,
      oss: report.oss ? { score: report.oss.score, classification: report.oss.classification } : undefined,
      businessRiskStatus: report.businessRiskStatus,
      recommendations: report.recommendationEngine?.recommendations,
      priorityTimeline: report.priorityTimeline,
      evidenceCoverageSummary: report.evidenceCoverageSummary,
      freshness: report.freshness
    };
    const serialized = JSON.stringify(customerRenderPayload);
    if (CUSTOMER_PDF_FORBIDDEN_PATTERN.test(serialized)) {
      throw new Error("PDF integrity validation failed: customer PDF payload contains internal-only intelligence.");
    }
  }
}

const ENTERPRISE_PDF = {
  margin: 54,
  ink: "#17201d",
  muted: "#52605a",
  line: "#d8ded6",
  surface: "#f6f8f5",
  surfaceAlt: "#eef3ed",
  brand: "#246b5b",
  accent: "#c27a2c",
  green: "#16845b",
  amber: "#b87500",
  red: "#b3261e",
  blue: "#2563eb",
  gray: "#64748b",
  white: "#ffffff"
};

type EnterpriseStatusTone = "green" | "amber" | "red" | "blue" | "gray";

function writeEnterpriseReportHeader(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const left = doc.page.margins.left;
  const width = enterpriseWidth(doc);
  const top = doc.page.margins.top;

  doc
    .font("Helvetica-Bold")
    .fontSize(16)
    .fillColor(ENTERPRISE_PDF.ink)
    .text("SYSTOLAB Revenue Health Diagnosis", left, top, { width: width - 90 })
    .font("Helvetica")
    .fontSize(9)
    .fillColor(ENTERPRISE_PDF.muted)
    .text("Generated by SYSTOLAB Intelligence Platform.", left, top + 22, { width: width - 90 })
    .fontSize(8)
    .text(`Generated: ${new Date().toISOString()}`, left, top + 35, { width: width - 90 });

  doc.moveTo(left, top + 50).lineTo(left + width, top + 50).strokeColor(ENTERPRISE_PDF.line).lineWidth(1).stroke();

  const barY = top + 64;
  const barHeight = 54;
  doc.roundedRect(left, barY, width, barHeight, 4).fillColor(ENTERPRISE_PDF.surface).fill().strokeColor(ENTERPRISE_PDF.line).lineWidth(1).stroke();

  const metadata = [
    ["Snapshot ID", report.snapshotId],
    ["Target URL", report.targetUrl],
    ["Captured", report.createdAt],
    ["Coverage", report.scanCoverage?.coverageLabel ?? "Not Available"]
  ] as const;
  const columnWidth = width / metadata.length;
  metadata.forEach(([label, value], index) => {
    const x = left + columnWidth * index;
    if (index > 0) {
      doc.moveTo(x, barY + 10).lineTo(x, barY + barHeight - 10).strokeColor(ENTERPRISE_PDF.line).lineWidth(1).stroke();
    }
    doc
      .font("Helvetica-Bold")
      .fontSize(7.5)
      .fillColor(ENTERPRISE_PDF.muted)
      .text(label.toUpperCase(), x + 10, barY + 10, { width: columnWidth - 20, lineBreak: false })
      .font("Helvetica")
      .fontSize(8.2)
      .fillColor(ENTERPRISE_PDF.ink)
      .text(pdfCleanText(value), x + 10, barY + 26, { width: columnWidth - 20 });
  });

  doc.y = barY + barHeight + 18;
}

function writeEnterpriseContinuationHeader(doc: PDFKit.PDFDocument): void {
  const left = doc.page.margins.left;
  const width = enterpriseWidth(doc);
  doc
    .font("Helvetica-Bold")
    .fontSize(11)
    .fillColor(ENTERPRISE_PDF.ink)
    .text("SYSTOLAB Revenue Health Diagnosis", left, doc.page.margins.top, { width: width - 90 })
    .font("Helvetica")
    .fontSize(8)
    .fillColor(ENTERPRISE_PDF.muted)
    .text("Generated by SYSTOLAB Intelligence Platform.", left, doc.page.margins.top + 16, { width: width - 90 });
  doc.moveTo(left, doc.page.margins.top + 34).lineTo(left + width, doc.page.margins.top + 34).strokeColor(ENTERPRISE_PDF.line).lineWidth(1).stroke();
  doc.y = doc.page.margins.top + 50;
}

function writeEnterpriseDecisionBrief(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const brief = pdfDecisionBrief(report);
  writeEnterpriseSectionLabel(doc, report, "SYSTOLAB Decision Intelligence Brief");

  writeEnterpriseBox(doc, report, "Executive Verdict", "green", 116, () => {
    doc
      .font("Helvetica-Bold")
      .fontSize(11)
      .fillColor(ENTERPRISE_PDF.ink)
      .text(brief.executiveVerdict.currentSituation, enterpriseInnerX(doc), doc.y, { width: enterpriseInnerWidth(doc) })
      .moveDown(0.35)
      .font("Helvetica")
      .fontSize(9.2)
      .fillColor(ENTERPRISE_PDF.muted)
      .text(brief.executiveVerdict.seriousness, { width: enterpriseInnerWidth(doc) })
      .moveDown(0.2)
      .text(brief.executiveVerdict.likelyBusinessImpact, { width: enterpriseInnerWidth(doc) });
  });

  const bannerTone = toneForActionClassification(brief.executiveActionBanner.classification);
  writeEnterpriseBox(doc, report, "Executive Action Banner", bannerTone, 78, () => {
    doc
      .font("Helvetica-Bold")
      .fontSize(13)
      .fillColor(colorForTone(bannerTone))
      .text(brief.executiveActionBanner.classification, enterpriseInnerX(doc), doc.y, { width: enterpriseInnerWidth(doc) })
      .font("Helvetica")
      .fontSize(9.2)
      .fillColor(ENTERPRISE_PDF.ink)
      .text(brief.executiveActionBanner.message, { width: enterpriseInnerWidth(doc) });
  }, 2);

  writeExecutiveDecisionMatrix(doc, report, brief);
  writeEnterpriseActionPlan(doc, report, brief);
  writeEnterpriseWhyThisMatters(doc, report, brief);
  writeEnterpriseCompetitivePosition(doc, report, brief);
  writeEnterpriseReliabilityPanel(doc, report, brief);
}

function writeExecutiveDecisionMatrix(
  doc: PDFKit.PDFDocument,
  report: ReportSnapshot,
  brief: ReportSnapshot["decisionIntelligenceBrief"]
): void {
  const matrix = brief.executiveDecisionMatrix;
  writeEnterpriseBox(doc, report, "Executive Decision Matrix", "gray", 330, () => {
    const score = matrix.executiveDecisionScore;
    const color = typeof score === "number" ? colorForScore(score) : ENTERPRISE_PDF.gray;
    const x = enterpriseInnerX(doc);
    const width = enterpriseInnerWidth(doc);

    doc.font("Helvetica-Bold").fontSize(9).fillColor(ENTERPRISE_PDF.ink).text("Executive Decision Score (EDS)", x, doc.y, { width });
    doc.y += 14;
    drawProgressBar(doc, x, doc.y, width, score, color);
    doc.y += 24;

    const rows: Array<[string, string]> = [
      ["EDS", formatPdfOss(score)],
      ["Risk Level", matrix.riskLevel],
      ["Executive Priority", matrix.executivePriority],
      ["Time Sensitivity", matrix.timeSensitivity],
      ["Competitive Position", matrix.competitivePosition],
      ["Primary Business Constraint", matrix.primaryBusinessConstraint],
      ["Potential Business Impact", matrix.potentialBusinessImpact],
      ["If Not Addressed Outcome", matrix.ifNotAddressedOutcome],
      ["Recommended Next Action", matrix.recommendedNextAction]
    ];

    rows.forEach(([label, value], index) => writeEnterpriseTableRow(doc, label, value, index));
  });
}

function writeEnterpriseActionPlan(
  doc: PDFKit.PDFDocument,
  report: ReportSnapshot,
  brief: ReportSnapshot["decisionIntelligenceBrief"]
): void {
  writeEnterpriseSectionLabel(doc, report, "Action Plan");
  const colors: EnterpriseStatusTone[] = ["red", "amber", "blue"];
  brief.actionPlan.slice(0, 3).forEach((item, index) => {
    writeEnterpriseBox(doc, report, item.priority, colors[index] ?? "blue", 94, () => {
      doc
        .font("Helvetica-Bold")
        .fontSize(9.5)
        .fillColor(ENTERPRISE_PDF.ink)
        .text(timeframeForPriority(index), enterpriseInnerX(doc), doc.y, { width: enterpriseInnerWidth(doc) })
        .font("Helvetica")
        .fontSize(9)
        .fillColor(ENTERPRISE_PDF.ink)
        .text(item.action, { width: enterpriseInnerWidth(doc) })
        .fillColor(ENTERPRISE_PDF.muted)
        .text(`Confidence: ${item.confidenceScore}% ${item.confidenceLevel}`, { width: enterpriseInnerWidth(doc) });
    }, 2);
  });
}

function writeEnterpriseWhyThisMatters(
  doc: PDFKit.PDFDocument,
  report: ReportSnapshot,
  brief: ReportSnapshot["decisionIntelligenceBrief"]
): void {
  writeEnterpriseBox(doc, report, "Why This Matters", "blue", 168, () => {
    const x = enterpriseInnerX(doc);
    const width = enterpriseInnerWidth(doc);
    doc
      .font("Helvetica")
      .fontSize(9.2)
      .fillColor(ENTERPRISE_PDF.ink)
      .text(brief.whyThisMatters.overallCondition, x, doc.y, { width })
      .moveDown(0.5);

    const half = (width - 12) / 2;
    const y = doc.y;
    drawMetricMiniCard(doc, x, y, half, "Strongest Validated Dimensions", brief.whyThisMatters.strongestValidatedDimensions.join(", ") || "Not Assessed", "green");
    drawMetricMiniCard(doc, x + half + 12, y, half, "Weakest Validated Dimension", brief.whyThisMatters.weakestValidatedDimension, "amber");
    doc.y = y + 70;
    doc.fillColor(ENTERPRISE_PDF.muted).font("Helvetica").fontSize(9).text(brief.whyThisMatters.businessSignificance, x, doc.y, { width });
  });
}

function writeEnterpriseCompetitivePosition(
  doc: PDFKit.PDFDocument,
  report: ReportSnapshot,
  brief: ReportSnapshot["decisionIntelligenceBrief"]
): void {
  writeEnterpriseBox(doc, report, "Competitive Position Analysis", toneForBenchmark(brief.competitivePositionAnalysis.benchmarkStatus), 176, () => {
    const x = enterpriseInnerX(doc);
    const width = enterpriseInnerWidth(doc);
    doc.font("Helvetica").fontSize(9.2).fillColor(ENTERPRISE_PDF.ink).text(brief.competitivePositionAnalysis.summary, x, doc.y, { width });
    doc.y += 10;
    writeEnterpriseTableRow(doc, "Benchmark Status", brief.competitivePositionAnalysis.benchmarkStatus, 0);
    writeEnterpriseTableRow(doc, "Competitor Status", brief.competitivePositionAnalysis.competitorStatus, 1);

    const positions = brief.competitivePositionAnalysis.dimensionPositions;
    if (positions.length > 0) {
      doc.moveDown(0.2).font("Helvetica-Bold").fontSize(8).fillColor(ENTERPRISE_PDF.muted).text("Benchmark Dimensions", x, doc.y, { width });
      positions.forEach((position, index) => {
        writeEnterpriseTableRow(doc, position.dimensionLabel, position.position, index + 2);
      });
    }
  });
}

function writeEnterpriseReliabilityPanel(
  doc: PDFKit.PDFDocument,
  report: ReportSnapshot,
  brief: ReportSnapshot["decisionIntelligenceBrief"]
): void {
  writeEnterpriseBox(doc, report, "Executive Reliability Panel", "gray", 230, () => {
    const reliability = brief.executiveReliabilityPanel;
    const metrics: Array<[string, string, EnterpriseStatusTone]> = [
      ["Evidence Coverage", reliability.evidenceCoverage, "gray"],
      ["Crawl Coverage", reliability.crawlCoverage, "gray"],
      ["Assessment Confidence", reliability.assessmentConfidence, toneForReliability(reliability.overallReportReliability)],
      ["Benchmark Confidence", reliability.benchmarkConfidence, "gray"],
      ["Assessment Trust Signals", reliability.assessmentTrustSignals, "green"],
      ["Overall Report Reliability", reliability.overallReportReliability, toneForReliability(reliability.overallReportReliability)]
    ];
    writeMetricGrid(doc, metrics);
    doc.moveDown(0.5);
    doc
      .font("Helvetica")
      .fontSize(8.5)
      .fillColor(ENTERPRISE_PDF.muted)
      .text(`Limitations: ${reliability.limitations.join(" ")}`, enterpriseInnerX(doc), doc.y, { width: enterpriseInnerWidth(doc) });
  });
}

function writeEnterpriseScoreOverview(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  writeEnterpriseSectionLabel(doc, report, "Executive Score Overview");
  writeEnterpriseBox(doc, report, "Website Condition Summary", "gray", 160, () => {
    const score = report.oss?.score ?? null;
    const metrics: Array<[string, string, EnterpriseStatusTone]> = [
      ["OSS", formatPdfOss(score), typeof score === "number" ? toneForScore(score) : "gray"],
      ["Business Risk", report.businessRiskStatus?.level ?? "Not Assessed", toneForRisk(report.businessRiskStatus?.classification ?? "UNKNOWN")],
      ["Evidence Coverage", `${report.evidenceCoverageSummary?.totalPagesSampled ?? 0} pages, ${report.evidenceCoverageSummary?.totalEvidenceObjects ?? 0} evidence objects`, "gray"],
      ["Confidence", report.confidenceEngine ? `${report.confidenceEngine.overallConfidenceScore}% ${report.confidenceEngine.confidenceLevel}` : "Not Available", "gray"]
    ];
    writeMetricGrid(doc, metrics);
  });
}

function writeEnterpriseRecommendedActions(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const recommendations = report.recommendationEngine?.recommendations ?? [];
  if (recommendations.length === 0) return;
  writeEnterpriseSectionLabel(doc, report, "Recommended Actions");
  recommendations.forEach((recommendation, index) => {
    const tone: EnterpriseStatusTone = recommendation.priority === "FIX NOW" ? "red" : recommendation.priority === "THIS MONTH" ? "amber" : "blue";
    writeEnterpriseBox(doc, report, `Action ${index + 1}: ${recommendation.priority}`, tone, 92, () => {
      doc
        .font("Helvetica-Bold")
        .fontSize(9.5)
        .fillColor(ENTERPRISE_PDF.ink)
        .text(recommendation.issue, enterpriseInnerX(doc), doc.y, { width: enterpriseInnerWidth(doc) })
        .font("Helvetica")
        .fontSize(9)
        .text(recommendation.action, { width: enterpriseInnerWidth(doc) })
        .fillColor(ENTERPRISE_PDF.muted)
        .text(`Confidence: ${recommendation.confidenceScore}%`, { width: enterpriseInnerWidth(doc) });
    }, 2);
  });
}

function writeEnterprisePriorityTimeline(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const timeline = report.priorityTimeline;
  if (!timeline) return;
  writeEnterpriseSectionLabel(doc, report, "Priority Timeline Framework");
  const groups = [
    ["FIX NOW", timeline.fixNow, "red"],
    ["THIS MONTH", timeline.thisMonth, "amber"],
    ["MONITOR", timeline.monitor, "blue"]
  ] as const;
  groups.forEach(([label, items, tone]) => {
    writeEnterpriseBox(doc, report, `${label} (${items.length})`, tone, 80 + Math.min(items.length, 3) * 32, () => {
      if (items.length === 0) {
        doc.font("Helvetica").fontSize(9).fillColor(ENTERPRISE_PDF.muted).text("No actions in this category.", enterpriseInnerX(doc), doc.y, { width: enterpriseInnerWidth(doc) });
        return;
      }
      items.forEach((item) => {
        doc
          .font("Helvetica-Bold")
          .fontSize(8.8)
          .fillColor(ENTERPRISE_PDF.ink)
          .text(`${item.timeWindow}: ${item.action}`, enterpriseInnerX(doc), doc.y, { width: enterpriseInnerWidth(doc) })
          .font("Helvetica")
          .fontSize(8)
          .fillColor(ENTERPRISE_PDF.muted)
          .text(`${item.structuralSeverity} severity | ${item.evidenceStrength} evidence`, { width: enterpriseInnerWidth(doc) })
          .moveDown(0.3);
      });
    });
  });
}

function writeEnterpriseEvidenceBoundary(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  writeEnterpriseSectionLabel(doc, report, "Evidence And Confidence Boundary");
  writeEnterpriseBox(doc, report, "Assessment Boundary", "gray", 124, () => {
    const totalPages = report.evidenceCoverageSummary?.totalPagesSampled ?? report.scanCoverage?.sampledPages ?? 0;
    const totalEvidence = report.evidenceCoverageSummary?.totalEvidenceObjects ?? report.evidenceObjects?.length ?? 0;
    const confidence = report.confidenceEngine?.overallConfidenceScore ?? pdfAverageConfidence(report.confidenceLayer ?? []);
    doc
      .font("Helvetica")
      .fontSize(9.2)
      .fillColor(ENTERPRISE_PDF.ink)
      .text(`This report is limited to validated evidence collected during the current scan. It does not infer unsupported revenue, intent, or business performance.`, enterpriseInnerX(doc), doc.y, { width: enterpriseInnerWidth(doc) })
      .moveDown(0.5);
    writeMetricGrid(doc, [
      ["Pages Sampled", String(totalPages), "gray"],
      ["Evidence Objects", String(totalEvidence), "gray"],
      ["Assessment Confidence", `${confidence}% ${pdfConfidenceLevel(confidence)}`, toneForReliability(pdfConfidenceLevel(confidence))]
    ]);
  });
}

function writeEnterpriseFreshness(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  if (!report.freshness) return;
  writeEnterpriseSectionLabel(doc, report, "Data Freshness");
  writeEnterpriseBox(doc, report, "Validity Window", "gray", 112, () => {
    writeMetricGrid(doc, [
      ["Captured", report.freshness.capturedAt, "gray"],
      ["Cache Status", report.freshness.cacheStatus, "gray"],
      ["Validity", `${report.freshness.validityWindowHours} hours`, "gray"],
      ["Staleness Risk", report.freshness.stalenessRisk, report.freshness.stalenessRisk === "high" ? "red" : report.freshness.stalenessRisk === "medium" ? "amber" : "green"]
    ]);
  });
}

function writeEnterpriseFooterAndPageNumbers(doc: PDFKit.PDFDocument): void {
  const range = doc.bufferedPageRange();
  for (let index = 0; index < range.count; index += 1) {
    doc.switchToPage(index);
    const pageNumber = index + 1;
    const left = doc.page.margins.left;
    const width = enterpriseWidth(doc);
    doc
      .font("Helvetica")
      .fontSize(8)
      .fillColor(ENTERPRISE_PDF.muted)
      .text(`Page ${pageNumber} of ${range.count}`, left + width - 90, doc.page.margins.top, { width: 90, align: "right" })
      .fillColor(ENTERPRISE_PDF.gray)
      .text("Generated by SYSTOLAB Intelligence Platform.", left, doc.page.height - 42, { width, align: "center" });
  }
}

function writeInternalFooterAndPageNumbers(doc: PDFKit.PDFDocument): void {
  const range = doc.bufferedPageRange();
  for (let index = 0; index < range.count; index += 1) {
    doc.switchToPage(index);
    const left = doc.page.margins.left;
    const width = enterpriseWidth(doc);
    doc
      .font("Helvetica-Bold")
      .fontSize(8)
      .fillColor(ENTERPRISE_PDF.red)
      .text("INTERNAL INTELLIGENCE REPORT - CONFIDENTIAL", left, doc.page.margins.top - 18, { width, align: "center" })
      .font("Helvetica")
      .fillColor(ENTERPRISE_PDF.muted)
      .text(`Page ${index + 1} of ${range.count}`, left + width - 90, doc.page.margins.top, { width: 90, align: "right" })
      .text("Generated by SYSTOLAB Intelligence Platform.", left, doc.page.height - 42, { width, align: "center" });
  }
}

function writeEnterpriseSectionLabel(doc: PDFKit.PDFDocument, report: ReportSnapshot, title: string): void {
  ensureEnterpriseSpace(doc, report, 54);
  doc
    .font("Helvetica-Bold")
    .fontSize(14)
    .fillColor(ENTERPRISE_PDF.ink)
    .text(title, doc.page.margins.left, doc.y, { width: enterpriseWidth(doc) });
  doc.y += 10;
}

function writeEnterpriseBox(
  doc: PDFKit.PDFDocument,
  report: ReportSnapshot,
  title: string,
  tone: EnterpriseStatusTone,
  minHeight: number,
  draw: () => void,
  borderWidth = 1
): void {
  ensureEnterpriseSpace(doc, report, minHeight);
  const x = doc.page.margins.left;
  const width = enterpriseWidth(doc);
  const y = doc.y;
  const headerHeight = 30;
  const color = colorForTone(tone);

  doc.rect(x, y, width, headerHeight).fillColor(tintForTone(tone)).fill();
  doc.rect(x, y, width, headerHeight).strokeColor(ENTERPRISE_PDF.line).lineWidth(1).stroke();
  doc
    .font("Helvetica-Bold")
    .fontSize(12)
    .fillColor(ENTERPRISE_PDF.ink)
    .text(title, x + 12, y + 9, { width: width - 24 });
  doc.moveTo(x, y + headerHeight).lineTo(x + width, y + headerHeight).strokeColor(color).lineWidth(borderWidth).stroke();

  doc.y = y + headerHeight + 12;
  draw();
  doc.y += 12;
  const height = Math.max(doc.y - y, minHeight);
  doc.rect(x, y, width, height).strokeColor(color).lineWidth(borderWidth).stroke();
  doc.y = y + height + 16;
}

function writeEnterpriseTableRow(doc: PDFKit.PDFDocument, label: string, value: string, index: number): void {
  const x = enterpriseInnerX(doc);
  const width = enterpriseInnerWidth(doc);
  const labelWidth = 142;
  const valueWidth = width - labelWidth - 16;
  const cleanValue = pdfCleanText(value);
  const rowHeight = Math.max(24, doc.heightOfString(cleanValue, { width: valueWidth }) + 12);
  if (index % 2 === 0) doc.rect(x, doc.y, width, rowHeight).fillColor(ENTERPRISE_PDF.surface).fill();
  doc
    .font("Helvetica-Bold")
    .fontSize(8.5)
    .fillColor(ENTERPRISE_PDF.muted)
    .text(label, x + 8, doc.y + 7, { width: labelWidth })
    .font("Helvetica")
    .fillColor(ENTERPRISE_PDF.ink)
    .text(cleanValue, x + labelWidth + 12, doc.y + 7, { width: valueWidth });
  doc.y += rowHeight;
}

function writeMetricGrid(doc: PDFKit.PDFDocument, metrics: Array<[string, string, EnterpriseStatusTone]>): void {
  const x = enterpriseInnerX(doc);
  const width = enterpriseInnerWidth(doc);
  const gap = 10;
  const columns = metrics.length >= 4 ? 2 : metrics.length;
  const cardWidth = (width - gap * (columns - 1)) / columns;
  const cardHeight = 54;
  let y = doc.y;
  metrics.forEach(([label, value, tone], index) => {
    const col = index % columns;
    if (index > 0 && col === 0) y += cardHeight + gap;
    drawMetricMiniCard(doc, x + col * (cardWidth + gap), y, cardWidth, label, value, tone);
  });
  doc.y = y + cardHeight;
}

function drawMetricMiniCard(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  width: number,
  label: string,
  value: string,
  tone: EnterpriseStatusTone
): void {
  doc.roundedRect(x, y, width, 54, 4).fillColor(ENTERPRISE_PDF.white).fill().strokeColor(ENTERPRISE_PDF.line).lineWidth(1).stroke();
  doc.rect(x, y, 4, 54).fillColor(colorForTone(tone)).fill();
  doc
    .font("Helvetica-Bold")
    .fontSize(7.2)
    .fillColor(ENTERPRISE_PDF.muted)
    .text(label.toUpperCase(), x + 10, y + 8, { width: width - 18, lineBreak: false })
    .font("Helvetica")
    .fontSize(8.4)
    .fillColor(ENTERPRISE_PDF.ink)
    .text(pdfCleanText(value), x + 10, y + 23, { width: width - 18 });
}

function drawProgressBar(doc: PDFKit.PDFDocument, x: number, y: number, width: number, score: number | null, color: string): void {
  const barHeight = 9;
  doc.roundedRect(x, y, width, barHeight, 4).fillColor(ENTERPRISE_PDF.surfaceAlt).fill();
  if (typeof score === "number") {
    const fillWidth = Math.max(0, Math.min(width, width * (score / 100)));
    doc.roundedRect(x, y, fillWidth, barHeight, 4).fillColor(color).fill();
  }
  doc
    .font("Helvetica-Bold")
    .fontSize(8)
    .fillColor(ENTERPRISE_PDF.ink)
    .text(typeof score === "number" ? `${score}/100` : "Not Scored", x, y + 13, { width, align: "right" });
}

function ensureEnterpriseSpace(doc: PDFKit.PDFDocument, report: ReportSnapshot, height: number): void {
  const bottom = doc.page.height - doc.page.margins.bottom - 54;
  if (doc.y + height <= bottom) return;
  doc.addPage();
  writeEnterpriseContinuationHeader(doc);
  doc.fillColor(ENTERPRISE_PDF.muted).font("Helvetica").fontSize(7).text(pdfCleanText(report.snapshotId), doc.page.margins.left, doc.y - 15, {
    width: enterpriseWidth(doc),
    align: "right"
  });
}

function enterpriseWidth(doc: PDFKit.PDFDocument): number {
  return doc.page.width - doc.page.margins.left - doc.page.margins.right;
}

function enterpriseInnerX(doc: PDFKit.PDFDocument): number {
  return doc.page.margins.left + 12;
}

function enterpriseInnerWidth(doc: PDFKit.PDFDocument): number {
  return enterpriseWidth(doc) - 24;
}

function pdfCleanText(value: unknown): string {
  return String(value ?? "Not Available").replace(/\s+/g, " ").trim();
}

function timeframeForPriority(index: number): string {
  if (index === 0) return "Timeframe: immediate corrective action";
  if (index === 1) return "Timeframe: high-impact optimization";
  return "Timeframe: long-term improvement or monitoring";
}

function toneForActionClassification(classification: ReportSnapshot["decisionIntelligenceBrief"]["executiveActionBanner"]["classification"]): EnterpriseStatusTone {
  if (classification === "Excellent" || classification === "Healthy but Optimize") return "green";
  if (classification === "Action Recommended") return "amber";
  if (classification === "High Risk" || classification === "Critical Attention Required") return "red";
  return "gray";
}

function toneForBenchmark(status: ReportSnapshot["decisionIntelligenceBrief"]["competitivePositionAnalysis"]["benchmarkStatus"]): EnterpriseStatusTone {
  if (status === "Above Benchmark") return "green";
  if (status === "At Benchmark") return "amber";
  if (status === "Below Benchmark") return "red";
  return "gray";
}

function toneForRisk(risk: ReportSnapshot["businessRiskStatus"]["classification"]): EnterpriseStatusTone {
  if (risk === "LOW") return "green";
  if (risk === "MEDIUM") return "amber";
  if (risk === "HIGH" || risk === "CRITICAL") return "red";
  return "gray";
}

function toneForReliability(reliability: ReportSnapshot["decisionIntelligenceBrief"]["executiveReliabilityPanel"]["overallReportReliability"]): EnterpriseStatusTone {
  if (reliability === "Very High" || reliability === "High") return "green";
  if (reliability === "Moderate") return "amber";
  return "gray";
}

function toneForScore(score: number): EnterpriseStatusTone {
  if (score >= 75) return "green";
  if (score >= 50) return "amber";
  return "red";
}

function colorForScore(score: number): string {
  if (score >= 75) return ENTERPRISE_PDF.green;
  if (score >= 50) return ENTERPRISE_PDF.amber;
  return ENTERPRISE_PDF.red;
}

function colorForTone(tone: EnterpriseStatusTone): string {
  if (tone === "green") return ENTERPRISE_PDF.green;
  if (tone === "amber") return ENTERPRISE_PDF.amber;
  if (tone === "red") return ENTERPRISE_PDF.red;
  if (tone === "blue") return ENTERPRISE_PDF.blue;
  return ENTERPRISE_PDF.gray;
}

function tintForTone(tone: EnterpriseStatusTone): string {
  if (tone === "green") return "#eef8f2";
  if (tone === "amber") return "#fff8e8";
  if (tone === "red") return "#fff1ef";
  if (tone === "blue") return "#eef4ff";
  return ENTERPRISE_PDF.surface;
}

function writeActionFirst(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Action First Panel");
  if (!report.actionFirstPanel?.items.length) {
    doc.fillColor("#52605a").fontSize(9).text(report.actionFirstPanel?.fallbackAction ?? "No action-first data available.").moveDown(0.8);
    return;
  }
  for (const item of report.actionFirstPanel.items) {
    doc
      .fontSize(9)
      .fillColor("#17201d")
      .text(`${item.actionId}: ${item.issue} (${item.effortLevel} effort)`)
      .fillColor("#52605a")
      .text(item.executableFix)
      .text(item.businessReason)
      .text(`${item.expectedDirectionalImpact.informationClarity}; ${item.expectedDirectionalImpact.conversionReadiness}; ${item.expectedDirectionalImpact.trustStrength}`)
      .text(`Evidence: ${item.evidenceIds.join(", ")}`)
      .moveDown(0.35);
  }
}

function writeSystemVerdict(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "System Verdict");
  doc
    .fontSize(10)
    .fillColor("#17201d")
    .text(report.systemVerdict?.line ?? report.decisionSummary)
    .fontSize(8)
    .fillColor("#52605a")
    .text(`Evidence: ${(report.systemVerdict?.evidenceIds ?? []).join(", ")}`)
    .moveDown(0.8);
}

function writeOssInterpretation(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const interpretation = report.ossInterpretation;
  sectionTitle(doc, "OSS Score Interpretation");
  doc
    .fontSize(9)
    .fillColor("#17201d")
    .text(`OSS ${formatPdfOss(report.oss?.score ?? null)} - ${interpretation?.label ?? report.oss?.classification ?? "Not Scored"}`)
    .fillColor("#52605a")
    .text(interpretation?.oneLineDiagnosis ?? report.executiveClarity?.primaryConversionBlocker ?? "OSS interpretation is unavailable for this snapshot.")
    .text(interpretation?.meaning ?? report.oss?.explanation ?? "No score explanation is available.")
    .moveDown(0.8);
}

function writeHeader(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  doc
    .fillColor("#17201d")
    .fontSize(22)
    .text(report.tenantBranding.reportTitle)
    .fontSize(10)
    .fillColor("#52605a")
    .text(report.tenantBranding.poweredByLabel)
    .moveDown(0.8);

  doc
    .fontSize(9)
    .text(`Snapshot ID: ${report.snapshotId}`)
    .text(`Target: ${report.targetUrl}`)
    .text(`Captured: ${report.createdAt}`)
    .text(`Coverage: ${report.scanCoverage.coverageLabel}`)
    .moveDown(1);
}

function writeDecisionIntelligenceBrief(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const brief = pdfDecisionBrief(report);
  sectionTitle(doc, "SYSTOLAB Decision Intelligence Brief");

  doc
    .fontSize(11)
    .fillColor("#17201d")
    .text("1. Executive Verdict")
    .fontSize(9)
    .text(brief.executiveVerdict.currentSituation)
    .fillColor("#52605a")
    .text(brief.executiveVerdict.seriousness)
    .text(brief.executiveVerdict.likelyBusinessImpact)
    .moveDown(0.45);

  doc
    .fontSize(11)
    .fillColor("#17201d")
    .text("2. Executive Action Banner")
    .fontSize(9)
    .text(`${brief.executiveActionBanner.classification} - ${brief.executiveActionBanner.urgency}`)
    .fillColor("#52605a")
    .text(brief.executiveActionBanner.message)
    .moveDown(0.45);

  const matrix = brief.executiveDecisionMatrix;
  doc
    .fontSize(11)
    .fillColor("#17201d")
    .text("3. Executive Decision Matrix")
    .fontSize(8.5)
    .text(`Executive Decision Score: ${formatPdfOss(matrix.executiveDecisionScore)}`)
    .text(`Risk Level: ${matrix.riskLevel}`)
    .text(`Executive Priority: ${matrix.executivePriority}`)
    .text(`Time Sensitivity: ${matrix.timeSensitivity}`)
    .text(`Competitive Position: ${matrix.competitivePosition}`)
    .text(`Primary Business Constraint: ${matrix.primaryBusinessConstraint}`)
    .text(`Potential Business Impact: ${matrix.potentialBusinessImpact}`)
    .text(`If Not Addressed: ${matrix.ifNotAddressedOutcome}`)
    .text(`Recommended Next Action: ${matrix.recommendedNextAction}`)
    .moveDown(0.45);

  doc.fontSize(11).fillColor("#17201d").text("4. Action Plan");
  for (const item of brief.actionPlan) {
    doc
      .fontSize(8.5)
      .fillColor("#17201d")
      .text(`${item.priority}: ${item.action}`)
      .fillColor("#52605a")
      .text(`${item.rationale} Confidence: ${item.confidenceScore}% ${item.confidenceLevel}.`)
      .moveDown(0.15);
  }
  doc.moveDown(0.3);

  doc
    .fontSize(11)
    .fillColor("#17201d")
    .text("5. Why This Matters")
    .fontSize(8.5)
    .text(brief.whyThisMatters.overallCondition)
    .text(`Strongest Validated Areas: ${brief.whyThisMatters.strongestValidatedDimensions.join(", ") || "Not Assessed"}`)
    .text(`Weakest Validated Area: ${brief.whyThisMatters.weakestValidatedDimension}`)
    .fillColor("#52605a")
    .text(brief.whyThisMatters.businessSignificance)
    .moveDown(0.45);

  doc
    .fontSize(11)
    .fillColor("#17201d")
    .text("6. Competitive Position Analysis")
    .fontSize(8.5)
    .text(brief.competitivePositionAnalysis.summary)
    .text(`Benchmark Status: ${brief.competitivePositionAnalysis.benchmarkStatus}`)
    .text(`Competitor Status: ${brief.competitivePositionAnalysis.competitorStatus}`)
    .moveDown(0.45);

  const reliability = brief.executiveReliabilityPanel;
  doc
    .fontSize(11)
    .fillColor("#17201d")
    .text("7. Executive Reliability Panel")
    .fontSize(8.5)
    .text(`Evidence Coverage: ${reliability.evidenceCoverage}`)
    .text(`Page Coverage: ${reliability.crawlCoverage}`)
    .text(`Assessment Confidence: ${reliability.assessmentConfidence}`)
    .text(`Benchmark Confidence: ${reliability.benchmarkConfidence}`)
    .text(`Trust Signals: ${reliability.assessmentTrustSignals}`)
    .text(`Report Reliability: ${reliability.overallReportReliability}`)
    .fillColor("#52605a")
    .text(`Limitations: ${reliability.limitations.join(" ")}`)
    .moveDown(0.9);
}

function writeVerdict(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const state = report.oss?.visualState ?? VISUAL_STATES[0];
  const clarity = report.executiveClarity;
  sectionTitle(doc, "3-Second Executive Clarity");
  doc
    .fontSize(26)
    .fillColor(state.color)
    .text(`${formatPdfOss(report.oss?.score ?? null)} ${state.label}`)
    .fontSize(10)
    .fillColor("#17201d")
    .text(`Overall Website Status: ${clarity?.overallWebsiteStatus ?? "Not Available"}`)
    .text(`Primary Conversion Blocker: ${clarity?.primaryConversionBlocker ?? "Not Available"}`)
    .text(`Primary Opportunity: ${clarity?.primaryOpportunity ?? "Not Available"}`)
    .text(`Estimated Impact Range: ${clarity?.estimatedImpactRange ?? "Not Available"}`)
    .text(`Recommended First Action: ${clarity?.recommendedFirstAction ?? "Not Available"}`)
    .moveDown(0.7);
  doc.fillColor("#52605a").text(report.oss?.explanation ?? "No score explanation is available for this snapshot.").moveDown(1);
}

function writeBusinessRisk(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Business Risk Status");
  const risk = report.businessRiskStatus;
  if (!risk) {
    doc.fillColor("#52605a").fontSize(9).text("Business Risk Status is unavailable for this snapshot.").moveDown(0.8);
    return;
  }
  doc
    .fontSize(10)
    .fillColor("#17201d")
    .text(risk.level)
    .fillColor("#52605a")
    .text(risk.primaryRiskDriver)
    .text(risk.explanation)
    .moveDown(0.8);
}

function writeEvidenceCoverage(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Evidence Coverage Summary");
  const coverage = report.evidenceCoverageSummary;
  if (!coverage) {
    doc.fillColor("#52605a").fontSize(9).text("Evidence coverage details are unavailable for this snapshot.").moveDown(0.8);
    return;
  }
  doc
    .fontSize(9)
    .fillColor("#52605a")
    .text(`${coverage.totalPagesSampled} pages sampled, ${coverage.totalEvidenceObjects} evidence objects.`);
  for (const page of coverage.pages ?? []) {
    doc.fillColor("#17201d").text(`${page.role}: ${page.coverageStatus} (${page.evidenceCount} EO) - ${page.url}`);
  }
  doc.moveDown(0.8);
}

function writeFreshness(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Data Freshness & Validity Window");
  if (!report.freshness) {
    doc.fillColor("#52605a").fontSize(9).text("Freshness details are unavailable for this snapshot.").moveDown(0.8);
    return;
  }
  doc
    .fontSize(9)
    .fillColor("#52605a")
    .text(`Captured: ${report.freshness.capturedAt}`)
    .text(`Cache: ${report.freshness.cacheStatus}; validity: ${report.freshness.validityWindowHours} hours; staleness risk: ${report.freshness.stalenessRisk}`)
    .text(`Next recommended scan: ${report.freshness.nextRecommendedScanAt}`)
    .moveDown(0.8);
}

function writeVitalSigns(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Business Vital Signs");
  const signs = report.businessVitalSigns ?? [];
  if (signs.length === 0) {
    doc.fillColor("#52605a").fontSize(9).text("Business Vital Signs are unavailable for this snapshot.").moveDown(0.8);
    return;
  }
  for (const sign of signs) {
    writeLineWithState(doc, `${sign.vitalSign}: ${sign.score} - ${sign.status}`, sign.visualState);
  }
  doc.moveDown(0.8);
}

function writeExecutiveTable(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Executive Summary");
  const rows = report.executiveSummaryTable ?? [];
  if (rows.length === 0) {
    doc.fillColor("#52605a").fontSize(9).text("Executive Summary details are unavailable for this snapshot.").moveDown(0.8);
    return;
  }
  for (const row of rows) {
    doc
      .fontSize(9)
      .fillColor("#17201d")
      .text(`${row.area}: ${row.currentStatus} | ${row.priorityLevel}`)
      .fillColor("#52605a")
      .text(`${row.observedCondition} ${row.businessImpact}`)
      .moveDown(0.35);
  }
}

function writeOutcomeBridge(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Business Outcome Bridge");
  const bridge = report.businessOutcomeBridge ?? [];
  if (bridge.length === 0) {
    doc.fillColor("#52605a").fontSize(9).text("Business Outcome Bridge is unavailable for this snapshot.").moveDown(0.8);
    return;
  }
  for (const item of bridge) {
    doc
      .fontSize(9)
      .fillColor("#17201d")
      .text(`${item.opportunityRange}: ${item.structuralFinding}`)
      .fillColor("#52605a")
      .text(item.mappedBusinessOutcome)
      .text(`${item.quantifiedUpliftRange.informationClarity}; ${item.quantifiedUpliftRange.conversionReadiness}; ${item.quantifiedUpliftRange.trustStrength}`)
      .text(item.transformationMapping)
      .text(`Evidence: ${item.evidenceIds.join(", ")}`)
      .moveDown(0.3);
  }
}

function writeRevenueIntelligence(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const revenue = report.revenueIntelligence as ReportSnapshot["revenueIntelligence"] | undefined;
  sectionTitle(doc, "Revenue Intelligence Engine");
  if (!revenue) {
    doc.fillColor("#52605a").fontSize(9).text("Revenue Intelligence is unavailable for this legacy snapshot. Re-run the scan to populate it.").moveDown(0.8);
    return;
  }

  doc
    .fontSize(9)
    .fillColor("#17201d")
    .text(`Status: ${revenue.status}; confidence: ${revenue.confidenceScore}%; competitor pressure: ${revenue.competitorRevenuePressure.pressureLevel}`)
    .fillColor("#52605a")
    .text(revenue.confidenceBasis);

  for (const estimate of [
    revenue.trafficRange,
    revenue.conversionPotentialRange,
    revenue.revenueOpportunityRange,
    revenue.opportunityCostRange
  ]) {
    doc
      .fillColor("#17201d")
      .text(`${estimate.label}: ${estimate.low}-${estimate.high} ${estimate.unit}`)
      .fillColor("#52605a")
      .text(`${estimate.rationale} EO ${estimate.evidenceIds.join(", ") || "No EO"}`);
  }
  doc.fillColor("#52605a").text(revenue.competitorRevenuePressure.explanation).moveDown(0.8);
}

function writeRecommendationEngine(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const engine = report.recommendationEngine as ReportSnapshot["recommendationEngine"] | undefined;
  sectionTitle(doc, "Recommendation Engine");
  if (!engine) {
    doc.fillColor("#52605a").fontSize(9).text("Recommendation Engine output is unavailable for this legacy snapshot. Re-run the scan to populate it.").moveDown(0.8);
    return;
  }

  doc.fontSize(9).fillColor("#52605a").text(engine.mappingSystem.explanation);
  for (const recommendation of engine.recommendations) {
    doc
      .fillColor("#17201d")
      .text(`${recommendation.recommendationId}: ${recommendation.priority} - ${recommendation.issue}`)
      .fillColor("#52605a")
      .text(recommendation.action)
      .text(`Projected score movement: +${recommendation.expectedScoreMovement}; confidence: ${recommendation.confidenceScore}%`)
      .text(recommendation.revenueIntelligenceMapping)
      .text(`Validation: ${recommendation.changeValidationPlan}`)
      .text(`Evidence: ${recommendation.evidenceIds.join(", ") || "No EO"}`)
      .moveDown(0.3);
  }
}

function writeOutcomeValidation(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const loop = report.recommendationOutcomeLoop as ReportSnapshot["recommendationOutcomeLoop"] | undefined;
  sectionTitle(doc, "Recommendation Outcome Validation Loop");
  if (!loop) {
    doc.fillColor("#52605a").fontSize(9).text("Outcome validation is unavailable for this legacy snapshot.").moveDown(0.8);
    return;
  }
  doc.fillColor("#52605a").fontSize(9).text(`Status: ${loop.status}; previous: ${loop.previousSnapshotId ?? "baseline"}`).text(loop.summary);
  for (const item of loop.validations) {
    doc
      .fillColor("#17201d")
      .text(`${item.recommendationId}: ${item.implementedStatus} | OSS ${item.ossDelta ?? "pending"}`)
      .fillColor("#52605a")
      .text(item.recommendation)
      .text(`Impact: ${item.revenueImpact.low}-${item.revenueImpact.high} ${item.revenueImpact.unit}; confidence ${item.confidenceScore}%`);
  }
  doc.moveDown(0.8);
}

function writeConfidenceEngine(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const confidence = report.confidenceEngine as ReportSnapshot["confidenceEngine"] | undefined;
  sectionTitle(doc, "Confidence Engine");
  if (!confidence) {
    doc.fillColor("#52605a").fontSize(9).text("Confidence Engine details are unavailable for this legacy snapshot.").moveDown(0.8);
    return;
  }
  doc.fillColor("#17201d").fontSize(9).text(`Overall: ${confidence.overallConfidenceScore}% ${confidence.confidenceLevel}`);
  for (const factor of confidence.factors) {
    doc.fillColor("#52605a").text(`${factor.label}: ${factor.score}% (${factor.weight}% weight) - ${factor.reason}`);
  }
  for (const item of confidence.estimateExplanations) {
    doc.fillColor("#17201d").text(`${item.area}: ${item.confidenceScore}%`).fillColor("#52605a").text(item.reasons.join(" "));
  }
  doc.moveDown(0.8);
}

function writeIndustryBenchmark(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const benchmark = report.industryBenchmarkEngine as ReportSnapshot["industryBenchmarkEngine"] | undefined;
  sectionTitle(doc, "Industry Benchmark Engine");
  if (!benchmark) {
    doc.fillColor("#52605a").fontSize(9).text("Industry Benchmark Engine is unavailable for this legacy snapshot.").moveDown(0.8);
    return;
  }
  doc.fillColor("#52605a").fontSize(9).text(`${benchmark.industryType}; ${benchmark.status}; sample size ${benchmark.sampleSize}`);
  for (const row of benchmark.currentPosition) {
    doc.fillColor("#17201d").text(`${row.dimensionLabel}: ${row.score} vs ${row.industryAverage} (${row.position}, ${row.delta >= 0 ? "+" : ""}${row.delta})`);
  }
  doc.fillColor("#52605a").text(benchmark.limitations.join(" ")).moveDown(0.8);
}

function writePriorityTimeline(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Priority Timeline Framework");
  const groups = [
    ["FIX NOW", report.priorityTimeline.fixNow],
    ["THIS MONTH", report.priorityTimeline.thisMonth],
    ["MONITOR", report.priorityTimeline.monitor]
  ] as const;
  for (const [label, items] of groups) {
    doc.fontSize(9).fillColor("#17201d").text(label);
    for (const item of items) {
      doc.fillColor("#52605a").text(`- ${item.timeWindow}: ${item.action} | EO ${item.evidenceIds.join(", ")}`);
    }
  }
  doc.moveDown(0.8);
}

function writeTransformation(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Transformation Intelligence Layer");
  if (!report.transformationIntelligence) {
    doc.fillColor("#52605a").fontSize(9).text("Transformation Intelligence is unavailable for this snapshot.").moveDown(0.8);
    return;
  }
  doc
    .fontSize(9)
    .fillColor("#17201d")
    .text(`Current OSS: ${report.transformationIntelligence.currentOss} | Projected OSS: ${report.transformationIntelligence.projectedOss} | Delta: +${report.transformationIntelligence.projectedDelta}`)
    .fillColor("#52605a")
    .text(report.transformationIntelligence.projectionBasis);
  for (const item of report.transformationIntelligence.dimensionProjections) {
    doc.text(`${item.dimensionLabel}: ${item.currentScore} -> ${item.projectedScore} (+${item.projectedDelta})`);
  }
  doc.moveDown(0.8);
}

function writeChangeDetection(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const changeDetection = report.lightweightChangeDetection as ReportSnapshot["lightweightChangeDetection"] | undefined;
  sectionTitle(doc, "Lightweight Change Detection");
  if (!changeDetection) {
    doc.fillColor("#52605a").fontSize(9).text("Change detection is unavailable for this legacy snapshot. Re-run the scan to create a baseline.").moveDown(0.8);
    return;
  }

  doc
    .fontSize(9)
    .fillColor("#52605a")
    .text(`Status: ${changeDetection.status}; compared snapshot: ${changeDetection.comparedSnapshotId ?? "baseline"}`)
    .text(changeDetection.explanation);
  for (const change of changeDetection.changes) {
    doc
      .fillColor("#17201d")
      .text(`${change.changeId}: ${change.area} ${change.beforeState} -> ${change.afterState} (${change.direction})`)
      .fillColor("#52605a")
      .text(`Confidence: ${change.confidenceScore}%; REC ${change.recommendationIds.join(", ") || "None"}; EO ${change.evidenceIds.join(", ") || "No EO"}`);
  }
  doc.moveDown(0.8);
}

function writeClosedLoop(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Closed-Loop Proof System");
  if (!report.closedLoopProofSystem) {
    doc.fillColor("#52605a").fontSize(9).text("Closed-loop proof data is unavailable for this snapshot.").moveDown(0.8);
    return;
  }
  doc
    .fontSize(9)
    .fillColor("#52605a")
    .text(`Status: ${report.closedLoopProofSystem.status}; baseline: ${report.closedLoopProofSystem.baselineSnapshotId}; before OSS: ${report.closedLoopProofSystem.beforeOss}`)
    .text(report.closedLoopProofSystem.explanation)
    .moveDown(0.8);
}

function writeMarketReadiness(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Market Readiness Position");
  if (!report.marketReadinessPosition) {
    doc.fillColor("#52605a").fontSize(9).text("Market readiness data is unavailable for this snapshot.").moveDown(0.8);
    return;
  }
  doc
    .fontSize(9)
    .fillColor("#52605a")
    .text(`${report.marketReadinessPosition.datasetLabel}; status: ${report.marketReadinessPosition.status}`)
    .text(report.marketReadinessPosition.limitation);
  for (const item of report.marketReadinessPosition.positions) {
    doc.fillColor("#17201d").text(`${item.dimensionLabel}: ${item.position} (${item.score})`);
  }
  doc.moveDown(0.8);
}

function writeGbpIdentity(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "GBP Identity Intelligence");
  if (!report.gbpIdentity) {
    doc.fillColor("#52605a").fontSize(9).text("GBP Identity Intelligence was not assessed in this scan.").moveDown(0.8);
    return;
  }
  doc
    .fontSize(9)
    .fillColor("#52605a")
    .text(`Status: ${report.gbpIdentity.status}; identity score: ${report.gbpIdentity.identityConsistencyScore}; mismatch flag: ${report.gbpIdentity.identityMismatchFlag}`)
    .text(`Confidence: ${report.gbpIdentity.confidenceScore}% ${report.gbpIdentity.confidenceLevel}; completeness: ${report.gbpIdentity.profileCompletenessLevel}`);
  for (const signal of report.gbpIdentity.signals) {
    doc.fillColor("#17201d").text(`${signal.label}: ${signal.status} - ${signal.observedValue}`);
  }
  doc.moveDown(0.8);
}

function writeCompetitorComparison(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Client vs Competitor Structural Comparison");
  if ((report.competitorComparison ?? []).length === 0) {
    doc.fillColor("#52605a").fontSize(9).text("Competitor Intelligence was not assessed in this scan.").moveDown(0.8);
    return;
  }
  for (const competitor of report.competitorComparison ?? []) {
    doc
      .fontSize(9)
      .fillColor("#17201d")
      .text(`${competitor.competitorLabel}: client OSS ${competitor.primaryOss}, competitor OSS ${competitor.competitorOss ?? "unavailable"}`)
      .fillColor("#52605a")
      .text(competitor.structuralGapSummary);
    for (const row of competitor.evidenceTraceabilityMap) {
      doc.text(`${row.dimensionLabel}: ${row.primaryScore} vs ${row.competitorScore ?? "N/A"} (${row.position}); client EO ${row.primaryEvidenceIds.join(", ")}; competitor EO ${row.competitorEvidenceIds.join(", ")}`);
    }
  }
  doc.moveDown(0.8);
}

function writeCompetitorIntelligence(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const engine = report.competitorIntelligenceEngine as ReportSnapshot["competitorIntelligenceEngine"] | undefined;
  sectionTitle(doc, "Competitor Intelligence Engine");
  if (!engine) {
    doc.fillColor("#52605a").fontSize(9).text("Competitor Intelligence Engine is unavailable for this legacy snapshot.").moveDown(0.8);
    return;
  }
  doc.fillColor("#52605a").fontSize(9).text(`Status: ${engine.status}; tracked competitors: ${engine.competitors.length}`).text(engine.explanation);
  for (const competitor of engine.competitors) {
    doc
      .fillColor("#17201d")
      .text(`${competitor.competitorLabel}: latest OSS movement ${competitor.latestMovement.ossDelta ?? "pending"}`)
      .fillColor("#52605a")
      .text(`${competitor.timeline.length} timeline point(s); ${competitor.competitorUrl}`);
  }
  doc.moveDown(0.8);
}

function writeDimensions(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Operational Dimension Scores");
  const dimensions = report.dimensions ?? [];
  if (dimensions.length === 0) {
    doc.fillColor("#52605a").fontSize(9).text("Operational dimension scores are unavailable for this snapshot.").moveDown(0.8);
    return;
  }
  for (const dimension of dimensions) {
    writeLineWithState(doc, `${dimension.label}: ${dimension.score} - ${dimension.classification}`, dimension.visualState);
  }
  doc.moveDown(0.8);
}

function writeDecisions(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "SYSTEM DECISION SUMMARY - ACTIONABLE STRUCTURAL OUTCOME");
  doc.fillColor("#17201d").fontSize(10).text(report.decisionSummary ?? "Decision summary is unavailable for this snapshot.").moveDown(0.6);
  for (const decision of report.decisions ?? []) {
    doc
      .fontSize(9)
      .fillColor("#17201d")
      .text(`${decision.category}: ${decision.decisionClassification}`)
      .fillColor("#52605a")
      .text(decision.impactExplanation)
      .text(decision.recommendedActionPath)
      .moveDown(0.4);
  }
}

function writeGroundTruthLog(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "Ground Truth Validation Log");
  for (const log of report.groundTruthValidationLog ?? []) {
    doc
      .fontSize(9)
      .fillColor("#17201d")
      .text(`${log.logId}: ${log.check} - ${log.outcome}`)
      .fillColor("#52605a")
      .text(`HTTP ${log.httpResult}; DOM ${log.domResult}; Render ${log.renderResult}; GTCS ${log.gtcsScore}%`)
      .text(log.gtcsMeaning)
      .text(`Evidence: ${log.evidenceIds.join(", ")} | Trace: ${log.validationTraceIds.join(", ")}`)
      .moveDown(0.35);
  }
}

function writeEvidenceDatabase(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const evidenceDatabase = report.evidenceDatabase as ReportSnapshot["evidenceDatabase"] | undefined;
  sectionTitle(doc, "Evidence Database");
  if (!evidenceDatabase) {
    doc.fillColor("#52605a").fontSize(9).text("Evidence Database is unavailable for this legacy snapshot.").moveDown(0.8);
    return;
  }
  for (const evidence of evidenceDatabase) {
    doc
      .fontSize(8)
      .fillColor("#17201d")
      .text(`${evidence.evidenceId}: ${evidence.issue} (${evidence.evidenceType})`)
      .fillColor("#52605a")
      .text(`Before: ${evidence.before ?? "none"}`)
      .text(`After: ${evidence.after ?? "none"}`)
      .text(`Confidence: ${evidence.confidenceScore}% - ${evidence.confidenceReason}`)
      .text(`Lineage: ${evidence.lineage.previousSnapshotId ?? "baseline"} -> ${evidence.lineage.snapshotId}; EO ${evidence.lineage.sourceEvidenceIds.join(", ")}`);
  }
  doc.moveDown(0.8);
}

function writeMonitoringAlerts(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const monitoring = report.monitoringScheduler as ReportSnapshot["monitoringScheduler"] | undefined;
  const alerts = report.alertEngine as ReportSnapshot["alertEngine"] | undefined;
  sectionTitle(doc, "Monitoring Scheduler & Alert Engine");
  if (!monitoring || !alerts) {
    doc.fillColor("#52605a").fontSize(9).text("Monitoring and alerts are unavailable for this legacy snapshot.").moveDown(0.8);
    return;
  }
  doc.fillColor("#52605a").fontSize(9).text(`${monitoring.status}; ${monitoring.cadence}; next run ${monitoring.nextRunAt}; channels ${monitoring.alertChannels.join(", ")}`);
  if (alerts.alerts.length === 0) doc.text("No alerts generated.");
  for (const alert of alerts.alerts) {
    doc.fillColor("#17201d").text(`${alert.severity}: ${alert.title}`).fillColor("#52605a").text(`${alert.message} Trigger: ${alert.trigger}`);
  }
  doc.moveDown(0.8);
}

function writeMemoryEvolution(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const graph = report.operationalMemoryGraph as ReportSnapshot["operationalMemoryGraph"] | undefined;
  const evolution = report.businessEvolutionEngine as ReportSnapshot["businessEvolutionEngine"] | undefined;
  const dna = report.businessDnaEngine as ReportSnapshot["businessDnaEngine"] | undefined;
  const threat = report.competitiveThreatRadar as ReportSnapshot["competitiveThreatRadar"] | undefined;
  const edit = report.editIntelligenceSystem as ReportSnapshot["editIntelligenceSystem"] | undefined;
  sectionTitle(doc, "Memory, Evolution, Threat, DNA, and Edit Intelligence");
  if (graph) doc.fillColor("#52605a").fontSize(9).text(`${graph.summary} Nodes ${graph.nodes.length}; edges ${graph.edges.length}.`);
  if (evolution) doc.text(`Evolution: ${evolution.trend}; delta ${evolution.scoreDelta}; ${evolution.causeNarrative}`);
  if (dna) doc.text(`Business DNA: strengths ${dna.strengths.join(", ")}; weaknesses ${dna.weaknesses.join(", ")}; growth ${dna.growthStyle}.`);
  if (threat) doc.text(`Threat Radar: ${threat.threatLevel}; ${threat.explanation}`);
  if (edit) doc.text(`Edit Intelligence: ${edit.status}; abandonment ${edit.abandonmentRisk}; churn ${edit.churnInference}.`);
  doc.moveDown(0.8);
}

function writeSystemHealth(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  sectionTitle(doc, "System Health Status");
  const health = report.systemHealthState;
  doc
    .fontSize(9)
    .fillColor("#52605a")
    .text(`Crawler stability: ${health.crawlerStability}`)
    .text(`Parser success rate: ${health.parserSuccessRate}%`)
    .text(`Render engine: ${health.renderEngineStatus}`)
    .text(`Memory: ${health.memoryUsageMb} MB; CPU load: ${health.cpuLoadPercent}% (${health.cpuUserMicros} user micros)`)
    .text(`Queue latency: ${health.queueLatencyMs} ms; error rate: ${Math.round(health.errorRate * 100)}%; reliability: ${health.overallReliability}`)
    .moveDown(0.8);
}

function writeEvidenceExplorer(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  doc.addPage();
  sectionTitle(doc, "Evidence Explorer");
  for (const evidence of report.evidenceObjects) {
    const traces = report.validationTrace.filter((trace) => trace.evidenceId === evidence.evidenceId);
    doc
      .fontSize(8)
      .fillColor("#17201d")
      .text(`${evidence.evidenceId} | ${evidence.sourceType.toUpperCase()} | GTCS ${evidence.groundTruthConfidence}%`)
      .fillColor("#52605a")
      .text(`Page: ${evidence.url}`)
      .text(`Selector: ${evidence.selectorPath ?? "Not applicable"}`)
      .text(`Raw: ${evidence.rawValue}`)
      .text(`Render: ${evidence.renderState ?? "not_rendered"}; visibility: ${evidence.renderVisibility ?? "not_applicable"}`)
      .text(`Validation: ${evidence.validationMethod ?? "not assigned"}; ${evidence.groundTruthMeaning ?? "GTCS meaning unavailable"}`)
      .text(`Trace: ${traces.map((trace) => `${trace.traceId} ${trace.outcome}`).join(" | ") || "No linked trace"}`)
      .moveDown(0.35);
  }
}

async function writeScreenshotEvidence(
  doc: PDFKit.PDFDocument,
  report: ReportSnapshot,
  getArtifact?: (artifactId: string) => Promise<Buffer | null>
): Promise<void> {
  const screenshotEvidence = report.evidenceObjects.filter((ev) => ev.screenshotRef);
  if (!screenshotEvidence.length || !getArtifact) return;

  doc.addPage();
  sectionTitle(doc, "Screenshot Evidence");
  doc.fontSize(8).fillColor("#52605a")
    .text("The following screenshots were captured during headless browser rendering and are linked to specific evidence objects.")
    .moveDown(0.6);

  for (const ev of screenshotEvidence) {
    if (!ev.screenshotRef) continue;

    doc
      .fontSize(8)
      .fillColor("#17201d")
      .text(`${ev.evidenceId} — ${ev.normalizedInput.signalKey}`)
      .fillColor("#52605a")
      .text(`Page: ${ev.url}`)
      .text(`Signal: ${ev.rawValue}`)
      .text(`Render state: ${ev.renderState ?? "not_rendered"}`)
      .text(`Verification: ${ev.renderVerification ?? "not available"}`)
      .moveDown(0.3);

    try {
      const imageBuffer = await getArtifact(ev.screenshotRef);
      if (imageBuffer) {
        const remainingHeight = doc.page.height - doc.page.margins.bottom - doc.y;
        const imgHeight = Math.min(220, remainingHeight - 20);
        if (imgHeight < 40) doc.addPage();
        doc.image(imageBuffer, { fit: [doc.page.width - doc.page.margins.left - doc.page.margins.right, imgHeight] });
        doc.moveDown(0.5);
      } else {
        doc.fillColor("#a0afa8").text("[Screenshot not available]").moveDown(0.3);
      }
    } catch {
      doc.fillColor("#a0afa8").text("[Screenshot could not be loaded]").moveDown(0.3);
    }
  }
}

async function writeCustomerScreenshotEvidence(
  doc: PDFKit.PDFDocument,
  report: ReportSnapshot,
  getArtifact?: (artifactId: string) => Promise<Buffer | null>
): Promise<void> {
  const screenshotEvidence = (report.evidenceObjects ?? []).filter((ev) => ev.screenshotRef);
  sectionTitle(doc, "Screenshot Evidence");
  if (!screenshotEvidence.length || !getArtifact) {
    doc
      .fontSize(9)
      .fillColor("#52605a")
      .text("Screenshot evidence is not available for this report export.")
      .moveDown(0.8);
    return;
  }

  doc
    .fontSize(8.5)
    .fillColor("#52605a")
    .text("Screenshots are included only when a captured evidence artifact is available for the customer report.")
    .moveDown(0.6);

  for (const ev of screenshotEvidence) {
    if (!ev.screenshotRef) continue;
    ensureLegacySectionSpace(doc, 120);
    doc
      .fontSize(8.5)
      .fillColor("#17201d")
      .text(`${ev.evidenceId} - ${ev.url}`)
      .fillColor("#52605a")
      .text(`Finding: ${pdfCleanText(ev.rawValue)}`)
      .moveDown(0.3);

    try {
      const imageBuffer = await getArtifact(ev.screenshotRef);
      if (imageBuffer) {
        const remainingHeight = doc.page.height - doc.page.margins.bottom - doc.y - 20;
        if (remainingHeight < 80) {
          doc.addPage();
          writeEnterpriseContinuationHeader(doc);
        }
        doc.image(imageBuffer, { fit: [enterpriseWidth(doc), Math.min(220, remainingHeight)] });
        doc.moveDown(0.5);
      } else {
        doc.fillColor("#a0afa8").text("[Screenshot not available]").moveDown(0.3);
      }
    } catch {
      doc.fillColor("#a0afa8").text("[Screenshot could not be loaded]").moveDown(0.3);
    }
  }
}

function writeArchitectureState(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const architecture = report.architectureState as ReportSnapshot["architectureState"] | undefined;
  sectionTitle(doc, "Layered Intelligence Architecture");
  if (!architecture) {
    doc.fillColor("#52605a").fontSize(9).text("Architecture state is unavailable for this legacy snapshot. Re-run the scan to populate it.").moveDown(0.8);
    return;
  }

  doc
    .fontSize(9)
    .fillColor("#17201d")
    .text(`Flow: ${architecture.flow.join(" -> ")}`)
    .fillColor("#52605a")
    .text(architecture.eventDrivenContract)
    .text(`Active V1 engines: ${architecture.activeV1Engines.join(", ")}`);
  for (const engine of architecture.stagedFutureEngines) {
    doc.fillColor("#17201d").text(`${engine.engine}: ${engine.status}`).fillColor("#52605a").text(engine.activationNote);
  }
  doc.moveDown(0.8);
}

function writeVisualFramework(doc: PDFKit.PDFDocument): void {
  doc.addPage();
  sectionTitle(doc, "SYSTOLAB Visual Intelligence Framework");
  for (const state of VISUAL_STATES) {
    writeLineWithState(doc, `${state.label} (${state.range[0]}-${state.range[1]}): ${state.businessMeaning}`, state);
  }
  doc.moveDown(1);
  doc
    .fillColor("#52605a")
    .fontSize(9)
    .text(
      "Visual Intelligence Colors represent observable website conditions only and must not be interpreted as business performance, revenue potential, search ranking position, market value, or future outcomes."
    );
}

function writeFooter(doc: PDFKit.PDFDocument, report: ReportSnapshot): void {
  const pages = doc.bufferedPageRange();
  for (let index = 0; index < pages.count; index += 1) {
    doc.switchToPage(index);
    doc
      .fontSize(8)
      .fillColor("#7b8580")
      .text(report.tenantBranding.footerLabel, 44, doc.page.height - 42, { align: "center" });
  }
}

function pdfDecisionBrief(report: ReportSnapshot): ReportSnapshot["decisionIntelligenceBrief"] {
  const candidate = (report as Partial<ReportSnapshot>).decisionIntelligenceBrief;
  if (
    candidate?.executiveVerdict &&
    candidate.executiveActionBanner &&
    candidate.executiveDecisionMatrix &&
    Array.isArray(candidate.actionPlan) &&
    candidate.whyThisMatters &&
    candidate.competitivePositionAnalysis &&
    candidate.executiveReliabilityPanel
  ) {
    return candidate;
  }

  const score = typeof report.oss?.score === "number" && report.oss.scoringStatus !== "not_scored" ? report.oss.score : null;
  if (score === null) return pdfUnavailableDecisionBrief(report);

  const dimensions = report.dimensions ?? [];
  const weakest = [...dimensions].sort((a, b) => a.score - b.score)[0];
  const strongest = [...dimensions].sort((a, b) => b.score - a.score).slice(0, 3);
  const recommendations = report.recommendationEngine?.recommendations ?? [];
  const firstAction = recommendations[0]?.action ?? report.actionFirstPanel?.items?.[0]?.executableFix ?? report.actionFirstPanel?.fallbackAction ?? "Review validated evidence before selecting the first structural change.";
  const coverage = report.evidenceCoverageSummary as Partial<ReportSnapshot["evidenceCoverageSummary"]> | undefined;
  const sampledPages = coverage?.totalPagesSampled ?? report.scanCoverage?.sampledPages ?? 0;
  const evidenceCount = coverage?.totalEvidenceObjects ?? report.evidenceObjects?.length ?? 0;
  const benchmarkStatus = pdfBenchmarkStatus(report);
  const competitorStatus = pdfCompetitorStatus(report);
  const confidenceScore = report.confidenceEngine?.overallConfidenceScore ?? pdfAverageConfidence(report.confidenceLayer ?? []);

  return {
    executiveVerdict: {
      currentSituation: `The website is scored at OSS ${score}/100 with ${(report.businessRiskStatus?.level ?? "not assessed").toLowerCase()}.`,
      seriousness: report.businessRiskStatus?.explanation ?? "Risk interpretation is limited to validated evidence.",
      firstAction,
      urgency: pdfTimeSensitivity(score),
      likelyBusinessImpact: pdfBusinessImpact(report, evidenceCount),
      evidenceBasis: `${sampledPages} sampled page${sampledPages === 1 ? "" : "s"} and ${evidenceCount} validated evidence object${evidenceCount === 1 ? "" : "s"} support this brief.`
    },
    executiveActionBanner: {
      classification: pdfClassification(score),
      message: weakest ? `Primary validated focus: ${weakest.label} at ${weakest.score}/100.` : "No single validated structural constraint was detected.",
      urgency: pdfTimeSensitivity(score)
    },
    executiveDecisionMatrix: {
      executiveDecisionScore: score,
      riskLevel: pdfRiskLevel(report.businessRiskStatus?.classification ?? "UNKNOWN"),
      executivePriority: pdfPriority(score),
      timeSensitivity: pdfTimeSensitivity(score),
      competitivePosition: benchmarkStatus,
      primaryBusinessConstraint: weakest ? `${weakest.label} is the lowest validated dimension at ${weakest.score}/100.` : report.businessRiskStatus?.primaryRiskDriver ?? "No primary constraint was validated.",
      potentialBusinessImpact: pdfBusinessImpact(report, evidenceCount),
      ifNotAddressedOutcome: report.systemVerdict?.businessConsequence ?? report.businessRiskStatus?.primaryRiskDriver ?? "No outcome projection was generated.",
      recommendedNextAction: firstAction
    },
    actionPlan: pdfActionPlan(report, weakest, firstAction, confidenceScore),
    whyThisMatters: {
      overallCondition: `The assessment is based on current observable website structure and produced OSS ${score}/100.`,
      strongestValidatedDimensions: strongest.map((dimension) => `${dimension.label} (${dimension.score}/100)`),
      weakestValidatedDimension: weakest ? `${weakest.label} (${weakest.score}/100)` : "No weak dimension was validated.",
      businessSignificance: report.systemVerdict?.businessConsequence ?? report.businessRiskStatus?.primaryRiskDriver ?? "Business significance is limited to validated evidence."
    },
    competitivePositionAnalysis: {
      summary: pdfCompetitiveSummary(benchmarkStatus, competitorStatus, report),
      benchmarkStatus,
      competitorStatus,
      dimensionPositions: (report.marketReadinessPosition?.positions ?? []).map((position) => ({
        dimension: position.dimension,
        dimensionLabel: position.dimensionLabel,
        position: position.position,
        confidenceScore: report.marketReadinessPosition?.comparativeConfidenceScore ?? 0,
        evidenceIds: position.evidenceIds
      }))
    },
    executiveReliabilityPanel: {
      evidenceCoverage: `${sampledPages} sampled page${sampledPages === 1 ? "" : "s"}, ${evidenceCount} validated evidence object${evidenceCount === 1 ? "" : "s"}.`,
      crawlCoverage: report.scanCoverage?.coverageLabel ?? "Not Available",
      assessmentConfidence: `${confidenceScore}% (${pdfConfidenceLevel(confidenceScore)})`,
      benchmarkConfidence: report.benchmarkContext?.comparativeConfidenceScore > 0 ? `${report.benchmarkContext.comparativeConfidenceScore}% (${report.benchmarkContext.status.replaceAll("_", " ")})` : "Not available",
      assessmentTrustSignals: pdfTrustSignalLabel(report),
      overallReportReliability: pdfConfidenceLevel(Math.min(confidenceScore, pdfCoverageReliability(sampledPages, evidenceCount))),
      limitations: pdfReliabilityLimitations(report)
    }
  };
}

function pdfUnavailableDecisionBrief(report: ReportSnapshot): ReportSnapshot["decisionIntelligenceBrief"] {
  return {
    executiveVerdict: {
      currentSituation: "Website content could not be collected, so the current situation cannot be scored from validated page evidence.",
      seriousness: "No structural risk level or revenue impact was inferred because evidence coverage is 0%.",
      firstAction: "Review website access, security, and robots settings before re-running the assessment.",
      urgency: "Not Applicable",
      likelyBusinessImpact: "Unable to calculate from validated current-scan evidence.",
      evidenceBasis: "0 sampled pages and 0 validated page evidence objects were available."
    },
    executiveActionBanner: {
      classification: "Unable to Assess",
      message: "Content was unavailable, so SYSTOLAB did not assign OSS, risk, competitor position, or revenue impact.",
      urgency: "Not Applicable"
    },
    executiveDecisionMatrix: {
      executiveDecisionScore: null,
      riskLevel: "Unable to Assess",
      executivePriority: "Not Applicable",
      timeSensitivity: "Not Applicable",
      competitivePosition: "Benchmark Data Unavailable",
      primaryBusinessConstraint: "Website content could not be collected.",
      potentialBusinessImpact: "Unable to calculate from validated current-scan evidence.",
      ifNotAddressedOutcome: "No outcome projection was generated because page evidence was unavailable.",
      recommendedNextAction: "Review access/security/robots settings and re-run scan."
    },
    actionPlan: [
      {
        priority: "Priority 1",
        action: "Review website access and security settings.",
        rationale: "The assessment could not collect page content, so access must be reviewed before conclusions can be generated.",
        confidenceScore: 0,
        confidenceLevel: "Limited",
        evidenceIds: []
      },
      {
        priority: "Priority 2",
        action: "Allow analysis access to public website content.",
        rationale: "Validated page content is required before OSS, recommendations, and benchmark position can be assessed.",
        confidenceScore: 0,
        confidenceLevel: "Limited",
        evidenceIds: []
      },
      {
        priority: "Priority 3",
        action: "Re-run the assessment after access is resolved.",
        rationale: "A new assessment is required to create validated evidence and score the website.",
        confidenceScore: 0,
        confidenceLevel: "Limited",
        evidenceIds: []
      }
    ],
    whyThisMatters: {
      overallCondition: "The report is limited to an access outcome, not a structural diagnosis.",
      strongestValidatedDimensions: [],
      weakestValidatedDimension: "Not assessed because website content was unavailable.",
      businessSignificance: "Business impact was not inferred because no current-scan page evidence was available."
    },
    competitivePositionAnalysis: {
      summary: "Benchmark and competitor position were not assessed because website content could not be collected.",
      benchmarkStatus: "Benchmark Data Unavailable",
      competitorStatus: "Competitor Data Unavailable",
      dimensionPositions: []
    },
    executiveReliabilityPanel: {
      evidenceCoverage: "0 sampled pages, 0 validated page evidence objects.",
      crawlCoverage: report.scanCoverage?.coverageLabel ?? "0% evidence coverage - content unavailable",
      assessmentConfidence: "0% (Limited)",
      benchmarkConfidence: "Not available",
      assessmentTrustSignals: "Not assessed because website content could not be collected.",
      overallReportReliability: "Limited",
      limitations: [
        "Website content could not be collected.",
        "OSS, business risk, revenue impact, and competitor position were not scored.",
        "Re-run the assessment after access is resolved."
      ]
    }
  };
}

function pdfActionPlan(
  report: ReportSnapshot,
  weakest: ReportSnapshot["dimensions"][number] | undefined,
  firstAction: string,
  confidenceScore: number
): ReportSnapshot["decisionIntelligenceBrief"]["actionPlan"] {
  const plan: ReportSnapshot["decisionIntelligenceBrief"]["actionPlan"] = [];
  const seen = new Set<string>();
  const push = (action: string, rationale: string, score: number, evidenceIds: string[]) => {
    const clean = action.trim();
    if (!clean || seen.has(clean.toLowerCase()) || plan.length >= 3) return;
    seen.add(clean.toLowerCase());
    plan.push({
      priority: `Priority ${plan.length + 1}` as "Priority 1" | "Priority 2" | "Priority 3",
      action: clean,
      rationale,
      confidenceScore: Math.max(0, Math.min(100, Math.round(score))),
      confidenceLevel: pdfConfidenceLevel(score),
      evidenceIds
    });
  };

  for (const recommendation of report.recommendationEngine?.recommendations ?? []) {
    push(recommendation.action, `${recommendation.issue}. ${recommendation.revenueIntelligenceMapping}`, recommendation.confidenceScore, recommendation.evidenceIds);
  }
  for (const item of report.actionFirstPanel?.items ?? []) {
    push(item.executableFix, item.businessReason, weakest?.confidenceScore ?? confidenceScore, item.evidenceIds);
  }
  if (weakest) {
    push(`Resolve the weakest validated dimension: ${weakest.label}.`, `${weakest.label} is currently the lowest validated dimension at ${weakest.score}/100.`, weakest.confidenceScore, weakest.evidenceIds);
  }
  push(firstAction, "This is the highest-priority action available from the report evidence.", confidenceScore, []);
  push("Re-run the assessment after priority fixes are implemented.", "A follow-up scan is required to validate whether observable structure improved.", Math.min(confidenceScore, 80), []);
  push("Review only validated report findings before selecting additional work.", "This keeps execution bounded to evidence collected during the current assessment.", confidenceScore, []);
  push("Prioritize fixes with explicit evidence support.", "Evidence-supported changes are required before SYSTOLAB can validate improvement in a later assessment.", confidenceScore, []);
  return plan;
}

function pdfClassification(score: number): ReportSnapshot["decisionIntelligenceBrief"]["executiveActionBanner"]["classification"] {
  if (score >= 90) return "Excellent";
  if (score >= 75) return "Healthy but Optimize";
  if (score >= 50) return "Action Recommended";
  if (score >= 25) return "High Risk";
  return "Critical Attention Required";
}

function pdfPriority(score: number): ReportSnapshot["decisionIntelligenceBrief"]["executiveDecisionMatrix"]["executivePriority"] {
  if (score >= 90) return "Monitor";
  if (score >= 75) return "Optimize";
  if (score >= 50) return "Improve";
  if (score >= 25) return "Act";
  return "Escalate";
}

function pdfTimeSensitivity(score: number): ReportSnapshot["decisionIntelligenceBrief"]["executiveDecisionMatrix"]["timeSensitivity"] {
  if (score >= 90) return "Monitor (Ongoing)";
  if (score >= 75) return "Short-Term (1-4 weeks)";
  if (score >= 50) return "This Month (7-30 days)";
  return "Immediate (0-7 days)";
}

function pdfRiskLevel(classification: ReportSnapshot["businessRiskStatus"]["classification"]): ReportSnapshot["decisionIntelligenceBrief"]["executiveDecisionMatrix"]["riskLevel"] {
  if (classification === "LOW") return "Low Risk";
  if (classification === "MEDIUM") return "Medium Risk";
  if (classification === "HIGH") return "High Risk";
  if (classification === "CRITICAL") return "Critical Risk";
  return "Unable to Assess";
}

function pdfBenchmarkStatus(report: ReportSnapshot): ReportSnapshot["decisionIntelligenceBrief"]["executiveDecisionMatrix"]["competitivePosition"] {
  const market = report.marketReadinessPosition;
  if (!market || market.status !== "available" || market.comparativeConfidenceScore <= 0) return "Benchmark Data Unavailable";
  const assessed = market.positions.filter((position) => position.position !== "Not Assessed");
  if (assessed.length === 0) return "Benchmark Data Unavailable";
  const above = assessed.filter((position) => position.position === "Above Benchmark").length;
  const below = assessed.filter((position) => position.position === "Below Benchmark").length;
  if (above > below) return "Above Benchmark";
  if (below > above) return "Below Benchmark";
  return "At Benchmark";
}

function pdfCompetitorStatus(report: ReportSnapshot): ReportSnapshot["decisionIntelligenceBrief"]["competitivePositionAnalysis"]["competitorStatus"] {
  const assessed = (report.competitorComparison ?? []).filter((comparison) => comparison.status === "assessed" && typeof comparison.competitorOss === "number");
  if (assessed.length === 0) return "Competitor Data Unavailable";
  const ahead = assessed.filter((comparison) => comparison.primaryOss >= (comparison.competitorOss ?? 0) + 3).length;
  const behind = assessed.filter((comparison) => (comparison.competitorOss ?? 0) >= comparison.primaryOss + 3).length;
  if (ahead > 0 && behind === 0) return "Ahead of Compared Competitors";
  if (behind > 0 && ahead === 0) return "Behind Compared Competitors";
  return "Mixed Position";
}

function pdfBusinessImpact(report: ReportSnapshot, evidenceCount: number): string {
  const revenue = report.revenueIntelligence;
  if (!revenue || evidenceCount <= 0 || revenue.status !== "estimated") return "Unable to calculate from validated current-scan evidence.";
  const range = revenue.revenueOpportunityRange;
  const formatter = new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 });
  return `${range.label}: ${formatter.format(range.low)}-${formatter.format(range.high)} ${range.unit.replaceAll("_", " ")}. This is a structural opportunity estimate, not actual revenue.`;
}

function pdfCompetitiveSummary(
  benchmarkStatus: ReportSnapshot["decisionIntelligenceBrief"]["competitivePositionAnalysis"]["benchmarkStatus"],
  competitorStatus: ReportSnapshot["decisionIntelligenceBrief"]["competitivePositionAnalysis"]["competitorStatus"],
  report: ReportSnapshot
): string {
  const dimensionCount = (report.marketReadinessPosition?.positions ?? []).filter((position) => position.position !== "Not Assessed").length;
  const benchmarkText =
    benchmarkStatus === "Benchmark Data Unavailable"
      ? "Benchmark comparison is unavailable from the current evidence."
      : `The site is ${benchmarkStatus.toLowerCase()} based on available benchmark dimensions.`;
  const competitorText =
    competitorStatus === "Competitor Data Unavailable"
      ? "No competitor conclusion was generated because competitor evidence was unavailable or not assessed."
      : `Compared competitor status: ${competitorStatus.toLowerCase()}.`;
  return `${benchmarkText} ${competitorText} ${dimensionCount} benchmark dimension${dimensionCount === 1 ? "" : "s"} had comparable evidence.`;
}

function pdfTrustSignalLabel(report: ReportSnapshot): string {
  const trustEvidence = (report.evidenceObjects ?? []).filter((evidence) => evidence.dimensionRefs?.includes("trust"));
  if (trustEvidence.length === 0) return "No trust evidence objects were validated in this scan.";
  return `${trustEvidence.length} trust evidence object${trustEvidence.length === 1 ? "" : "s"} validated.`;
}

function pdfReliabilityLimitations(report: ReportSnapshot): string[] {
  const limitations: string[] = [];
  if (report.benchmarkContext?.status !== "available") limitations.push("Benchmark confidence is limited by available comparison coverage.");
  if ((report.competitorComparison ?? []).filter((comparison) => comparison.status === "assessed").length === 0) {
    limitations.push("Competitor position is unavailable because no competitor comparison completed with validated evidence.");
  }
  if (report.revenueIntelligence?.status !== "estimated") limitations.push("Revenue impact is not calculated when current evidence is input-limited.");
  if ((report.evidenceCoverageSummary?.totalPagesSampled ?? report.scanCoverage?.sampledPages ?? 0) < 2) limitations.push("Coverage is based on a small page sample.");
  return limitations.length > 0 ? limitations : ["No additional reliability limitation was detected beyond standard evidence-bound interpretation."];
}

function pdfAverageConfidence(confidenceLayer: ReportSnapshot["confidenceLayer"]): number {
  if (confidenceLayer.length === 0) return 0;
  return Math.max(0, Math.min(100, Math.round(confidenceLayer.reduce((sum, item) => sum + item.confidenceScore, 0) / confidenceLayer.length)));
}

function pdfCoverageReliability(sampledPages: number, evidenceCount: number): number {
  if (sampledPages <= 0 || evidenceCount <= 0) return 0;
  if (sampledPages >= 3 && evidenceCount >= 20) return 90;
  if (sampledPages >= 2 && evidenceCount >= 10) return 80;
  if (sampledPages >= 1 && evidenceCount >= 5) return 70;
  return 55;
}

function pdfConfidenceLevel(score: number): ReportSnapshot["decisionIntelligenceBrief"]["executiveReliabilityPanel"]["overallReportReliability"] {
  const safeScore = Math.max(0, Math.min(100, Math.round(score)));
  if (safeScore >= 90) return "Very High";
  if (safeScore >= 80) return "High";
  if (safeScore >= 70) return "Moderate";
  return "Limited";
}

function formatPdfOss(score: number | null): string {
  return typeof score === "number" ? `${score}/100` : "Not Scored";
}

function sectionTitle(doc: PDFKit.PDFDocument, title: string): void {
  ensureLegacySectionSpace(doc, 52);
  const x = doc.page.margins.left;
  const width = enterpriseWidth(doc);
  const y = doc.y;
  doc
    .roundedRect(x, y, width, 30, 4)
    .fillColor(ENTERPRISE_PDF.surface)
    .fill()
    .strokeColor(ENTERPRISE_PDF.line)
    .lineWidth(1)
    .stroke();
  doc
    .font("Helvetica-Bold")
    .fontSize(11.5)
    .fillColor("#17201d")
    .text(title, x + 12, y + 9, { width: width - 24 });
  doc.y = y + 40;
}

function ensureLegacySectionSpace(doc: PDFKit.PDFDocument, height: number): void {
  const bottom = doc.page.height - doc.page.margins.bottom - 54;
  if (doc.y + height <= bottom) return;
  doc.addPage();
  writeEnterpriseContinuationHeader(doc);
}

function writeLineWithState(doc: PDFKit.PDFDocument, text: string, state: VisualState): void {
  doc.fillColor(state.color).fontSize(9).text("■", { continued: true });
  doc.fillColor("#17201d").text(` ${text}`);
}
