import mongoose, { Schema } from "mongoose";
import type { TenantBranding } from "@systolab/shared";

export type TenantAttributionMode = "systolab" | "partner" | "hidden";

export interface TenantDocument extends mongoose.Document {
  slug: string;
  publicName: string;
  logoUrl?: string;
  faviconUrl?: string;
  customDomain?: string;
  primaryColor: string;
  secondaryColor?: string;
  accentColor: string;
  typography?: string;
  loginBackgroundUrl?: string;
  dashboardWelcomeMessage?: string;
  emailSenderName?: string;
  supportEmail?: string;
  privacyPolicyUrl?: string;
  termsOfServiceUrl?: string;
  attributionMode?: TenantAttributionMode;
  assistantName?: string;
  reportTitle: string;
  reportFooter?: string;
  customReportLabels?: Record<string, string>;
  poweredByLabel: string;
  footerLabel: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const TenantSchema = new Schema<TenantDocument>(
  {
    slug: { type: String, required: true, unique: true, index: true },
    publicName: { type: String, required: true },
    logoUrl: { type: String },
    faviconUrl: { type: String },
    customDomain: { type: String, index: true },
    primaryColor: { type: String, default: "#246b5b" },
    secondaryColor: { type: String },
    accentColor: { type: String, default: "#c27a2c" },
    typography: { type: String },
    loginBackgroundUrl: { type: String },
    dashboardWelcomeMessage: { type: String },
    emailSenderName: { type: String },
    supportEmail: { type: String },
    privacyPolicyUrl: { type: String },
    termsOfServiceUrl: { type: String },
    attributionMode: { type: String, enum: ["systolab", "partner", "hidden"], default: "systolab" },
    assistantName: { type: String },
    reportTitle: { type: String, default: "SYSTOLAB Revenue Health Diagnosis" },
    reportFooter: { type: String },
    customReportLabels: { type: Schema.Types.Mixed },
    poweredByLabel: { type: String, default: "Powered by SYSTOLAB Revenue Intelligence Engine" },
    footerLabel: { type: String, default: "Generated by SYSTOLAB Revenue Intelligence Platform" },
    isActive: { type: Boolean, default: true }
  },
  { timestamps: true, minimize: false }
);

export const Tenant = mongoose.model<TenantDocument>("Tenant", TenantSchema);

export function tenantToBranding(tenant: TenantDocument): TenantBranding {
  return {
    tenantId: tenant.id,
    slug: tenant.slug,
    publicName: tenant.publicName,
    logoUrl: tenant.logoUrl,
    faviconUrl: tenant.faviconUrl,
    primaryColor: tenant.primaryColor,
    secondaryColor: tenant.secondaryColor,
    accentColor: tenant.accentColor,
    typography: tenant.typography,
    loginBackgroundUrl: tenant.loginBackgroundUrl,
    dashboardWelcomeMessage: tenant.dashboardWelcomeMessage,
    emailSenderName: tenant.emailSenderName,
    supportEmail: tenant.supportEmail,
    privacyPolicyUrl: tenant.privacyPolicyUrl,
    termsOfServiceUrl: tenant.termsOfServiceUrl,
    attributionMode: tenant.attributionMode,
    assistantName: tenant.assistantName,
    reportTitle: tenant.reportTitle,
    reportFooter: tenant.reportFooter,
    customReportLabels: tenant.customReportLabels,
    poweredByLabel: tenant.poweredByLabel,
    footerLabel: tenant.footerLabel,
    customDomain: tenant.customDomain
  };
}

export function defaultBranding(): TenantBranding {
  return {
    tenantId: "default",
    slug: "systolab",
    publicName: "SYSTOLAB",
    primaryColor: "#246b5b",
    accentColor: "#c27a2c",
    attributionMode: "systolab",
    assistantName: "SYSTOLAB Intelligence Assistant",
    reportTitle: "SYSTOLAB Revenue Health Diagnosis",
    poweredByLabel: "Powered by SYSTOLAB Revenue Intelligence Engine",
    footerLabel: "Generated by SYSTOLAB Revenue Intelligence Platform"
  };
}
