import mongoose, { Schema } from "mongoose";
import type { TenantBranding } from "@systolab/shared";

export interface TenantDocument extends mongoose.Document {
  slug: string;
  publicName: string;
  logoUrl?: string;
  customDomain?: string;
  primaryColor: string;
  accentColor: string;
  reportTitle: string;
  poweredByLabel: string;
  footerLabel: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const TenantSchema = new Schema<TenantDocument>(
  {
    slug: { type: String, required: true, unique: true, index: true },
    publicName: { type: String, required: true },
    logoUrl: { type: String },
    customDomain: { type: String, index: true },
    primaryColor: { type: String, default: "#246b5b" },
    accentColor: { type: String, default: "#c27a2c" },
    reportTitle: { type: String, default: "SYSTOLAB Revenue Health Diagnosis" },
    poweredByLabel: { type: String, default: "Powered by SYSTOLAB Revenue Intelligence Engine" },
    footerLabel: { type: String, default: "Generated by SYSTOLAB Revenue Intelligence Platform" },
    isActive: { type: Boolean, default: true }
  },
  { timestamps: true }
);

export const Tenant = mongoose.model<TenantDocument>("Tenant", TenantSchema);

export function tenantToBranding(tenant: TenantDocument): TenantBranding {
  return {
    tenantId: tenant.id,
    slug: tenant.slug,
    publicName: tenant.publicName,
    logoUrl: tenant.logoUrl,
    primaryColor: tenant.primaryColor,
    accentColor: tenant.accentColor,
    reportTitle: tenant.reportTitle,
    poweredByLabel: tenant.poweredByLabel,
    footerLabel: tenant.footerLabel,
    customDomain: tenant.customDomain
  };
}

export function defaultBranding(): TenantBranding {
  return {
    tenantId: "default",
    slug: "systolab",
    publicName: "SYSTOLAB",
    primaryColor: "#246b5b",
    accentColor: "#c27a2c",
    reportTitle: "SYSTOLAB Revenue Health Diagnosis",
    poweredByLabel: "Powered by SYSTOLAB Revenue Intelligence Engine",
    footerLabel: "Generated by SYSTOLAB Revenue Intelligence Platform"
  };
}
