import mongoose, { Schema } from "mongoose";
import type { TenantBranding } from "@systolab/shared";

export type TenantAttributionMode = "systolab" | "partner" | "hidden";

export interface TenantDocument extends mongoose.Document {
  slug: string;
  publicName: string;
  logoUrl?: string;
  faviconUrl?: string;
  websiteUrl?: string;
  phoneNumber?: string;
  officeAddress?: string;
  businessRegistration?: string;
  licenseNumber?: string;
  socialLinks?: string[];
  consultantName?: string;
  disclaimerText?: string;
  coverPageDesign?: TenantBranding["coverPageDesign"];
  qrCodeUrl?: string;
  whatsappLink?: string;
  calendarBookingLink?: string;
  digitalSignature?: string;
  serviceOfferings?: string[];
  poweredByMode?: TenantBranding["poweredByMode"];
  customDomain?: string;
  primaryColor: string;
  secondaryColor?: string;
  accentColor: string;
  typography?: string;
  loginBackgroundUrl?: string;
  dashboardWelcomeMessage?: string;
  emailSenderName?: string;
  supportEmail?: string;
  privacyPolicyUrl?: string;
  termsOfServiceUrl?: string;
  attributionMode?: TenantAttributionMode;
  assistantName?: string;
  reportTitle: string;
  reportFooter?: string;
  customReportLabels?: Record<string, string>;
  poweredByLabel: string;
  footerLabel: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const TenantSchema = new Schema<TenantDocument>(
  {
    slug: { type: String, required: true, unique: true, index: true },
    publicName: { type: String, required: true },
    logoUrl: { type: String },
    faviconUrl: { type: String },
    websiteUrl: { type: String },
    phoneNumber: { type: String },
    officeAddress: { type: String },
    businessRegistration: { type: String },
    licenseNumber: { type: String },
    socialLinks: { type: [String], default: [] },
    consultantName: { type: String },
    disclaimerText: { type: String },
    coverPageDesign: { type: String, enum: ["classic", "executive", "minimal"], default: "executive" },
    qrCodeUrl: { type: String },
    whatsappLink: { type: String },
    calendarBookingLink: { type: String },
    digitalSignature: { type: String },
    serviceOfferings: { type: [String], default: ["SEO", "Website Development", "Google Ads", "CRO", "Local SEO", "AI Search Optimization"] },
    poweredByMode: { type: String, enum: ["full_white_label", "co_branded", "systolab_standard"], default: "systolab_standard" },
    customDomain: { type: String, index: true },
    primaryColor: { type: String, default: "#246b5b" },
    secondaryColor: { type: String },
    accentColor: { type: String, default: "#c27a2c" },
    typography: { type: String },
    loginBackgroundUrl: { type: String },
    dashboardWelcomeMessage: { type: String },
    emailSenderName: { type: String },
    supportEmail: { type: String },
    privacyPolicyUrl: { type: String },
    termsOfServiceUrl: { type: String },
    attributionMode: { type: String, enum: ["systolab", "partner", "hidden"], default: "systolab" },
    assistantName: { type: String },
    reportTitle: { type: String, default: "Website Growth & Decision Intelligence Report" },
    reportFooter: { type: String },
    customReportLabels: { type: Schema.Types.Mixed },
    poweredByLabel: { type: String, default: "Powered by SYSTOLAB Revenue Intelligence Engine" },
    footerLabel: { type: String, default: "Generated by SYSTOLAB Revenue Intelligence Platform" },
    isActive: { type: Boolean, default: true }
  },
  { timestamps: true, minimize: false }
);

export const Tenant = mongoose.model<TenantDocument>("Tenant", TenantSchema);

export function tenantToBranding(tenant: TenantDocument): TenantBranding {
  return {
    tenantId: tenant.id,
    slug: tenant.slug,
    publicName: tenant.publicName,
    logoUrl: tenant.logoUrl,
    faviconUrl: tenant.faviconUrl,
    websiteUrl: tenant.websiteUrl,
    phoneNumber: tenant.phoneNumber,
    officeAddress: tenant.officeAddress,
    businessRegistration: tenant.businessRegistration,
    licenseNumber: tenant.licenseNumber,
    socialLinks: tenant.socialLinks ?? [],
    consultantName: tenant.consultantName,
    disclaimerText: tenant.disclaimerText,
    coverPageDesign: tenant.coverPageDesign,
    qrCodeUrl: tenant.qrCodeUrl,
    whatsappLink: tenant.whatsappLink,
    calendarBookingLink: tenant.calendarBookingLink,
    digitalSignature: tenant.digitalSignature,
    serviceOfferings: tenant.serviceOfferings ?? [],
    poweredByMode: tenant.poweredByMode,
    primaryColor: tenant.primaryColor,
    secondaryColor: tenant.secondaryColor,
    accentColor: tenant.accentColor,
    typography: tenant.typography,
    loginBackgroundUrl: tenant.loginBackgroundUrl,
    dashboardWelcomeMessage: tenant.dashboardWelcomeMessage,
    emailSenderName: tenant.emailSenderName,
    supportEmail: tenant.supportEmail,
    privacyPolicyUrl: tenant.privacyPolicyUrl,
    termsOfServiceUrl: tenant.termsOfServiceUrl,
    attributionMode: tenant.attributionMode,
    assistantName: tenant.assistantName,
    reportTitle: tenant.reportTitle || "Website Growth & Decision Intelligence Report",
    reportFooter: tenant.reportFooter,
    customReportLabels: tenant.customReportLabels,
    poweredByLabel: tenant.poweredByLabel,
    footerLabel: tenant.footerLabel,
    customDomain: tenant.customDomain
  };
}

export function defaultBranding(): TenantBranding {
  return {
    tenantId: "default",
    slug: "systolab",
    publicName: "SYSTOLAB",
    primaryColor: "#246b5b",
    accentColor: "#c27a2c",
    attributionMode: "systolab",
    assistantName: "SYSTOLAB Intelligence Assistant",
    websiteUrl: "https://systolab.com",
    serviceOfferings: ["SEO", "Website Development", "Google Ads", "CRO", "Local SEO", "AI Search Optimization"],
    poweredByMode: "systolab_standard",
    reportTitle: "Website Growth & Decision Intelligence Report",
    poweredByLabel: "Powered by SYSTOLAB Revenue Intelligence Engine",
    footerLabel: "Generated by SYSTOLAB Revenue Intelligence Platform"
  };
}
