import { describe, expect, it } from "vitest";
import { visualStateForScore, type ReportSnapshot } from "@systolab/shared";
import { renderReportPdf } from "./services/pdfService.js";

describe("enterprise PDF report rendering", () => {
  it("renders an executive PDF with SYSTOLAB branding and without internal diagnostic sections", async () => {
    const pdf = await renderReportPdf(makeEnterpriseReport());
    const text = pdf.toString("latin1");

    expect(text).toContain("SYSTOLAB Customer Intelligence Report");
    expect(text).toContain("Customer-facing business and visibility intelligence generated by SYSTOLAB.");
    expect(text).toContain("SYSTOLAB Decision Intelligence Brief");
    expect(text).toContain("Website Intelligence Report");
    expect(text).toContain("Visibility Intelligence Report");
    expect(text).toContain("Business Opportunity Boundary");
    expect(text).toContain("Business Decision Summary");
    expect(text).toContain("Priority Action Summary");
    expect(text).toContain("Local Presence Intelligence");
    expect(text).toContain("Customer Question Coverage");
    expect(text).toContain("Website vs Competitor Content Comparison");
    expect(text).toContain("Why Competitors Are Winning");
    expect(text).toContain("Revenue Leakage Analysis");
    expect(text).toContain("What Affects Revenue Most");
    expect(text).toContain("What To Fix Before Other Work");
    expect(text).toContain("Implementation Roadmap");
    expect(text).toContain("Customer Action Center");
    expect(pdfPageCount(text)).toBeGreaterThanOrEqual(4);
    expect(pdfPageCount(text)).toBeLessThanOrEqual(30);
    expect(text).not.toMatch(/Full Customer Intelligence Report|Revenue Intelligence Engine|Recommendation Outcome Validation Loop|Evidence Database|Global Output Contract|Action Plan Mapping|canonical issue|Dependency Intelligence|Business Outcome Attribution|Recommendation Sequencing|SEO Intelligence Report|GBP \/ Local/i);
    expect(text).not.toMatch(/System Health Status|Evidence Explorer|Ground Truth Validation Log|Layered Intelligence Architecture|Parser success|Crawler stability|rawSignalTelemetry|executionProvenance|validationTrace/i);
    expect(text).not.toMatch(/EV-\d+|EO-\d+|REC-\d+|Snapshot ID/i);
  });

  it("sanitizes raw internal snapshot terms before customer PDF integrity validation", async () => {
    const report = makeEnterpriseReport();
    report.businessRiskStatus.explanation = "Parser success rawSignalTelemetry executionProvenance should remain internal.";
    report.recommendationEngine.recommendations[0].issue = "HTTP fetch failed parser success rawSignalTelemetry executionProvenance.";
    report.recommendationEngine.recommendations[0].revenueIntelligenceMapping = "Crawler diagnostics and recovery logs are internal.";
    report.priorityTimeline.thisMonth[0].action = "Review crawler diagnostics and parser logs internally.";
    report.freshness.cacheStatus = "crawler diagnostics" as ReportSnapshot["freshness"]["cacheStatus"];

    const pdf = await renderReportPdf(report);
    const text = pdf.toString("latin1");

    expect(text).toContain("SYSTOLAB Customer Intelligence Report");
    expect(text).not.toMatch(/HTTP fetch failed|parser success|rawSignalTelemetry|executionProvenance|crawler diagnostics|recovery logs/i);
  });
});

function pdfPageCount(text: string): number {
  return Number(text.match(/\/Count\s+(\d+)/)?.[1] ?? 0);
}

function makeEnterpriseReport(): ReportSnapshot {
  return {
    snapshotId: "snap_pdf_enterprise",
    createdAt: "2026-06-15T06:00:00.000Z",
    targetUrl: "https://example.com",
    status: "completed",
    mode: "fast_scan",
    tenantBranding: {
      tenantId: "tenant_pdf",
      slug: "systolab",
      publicName: "SYSTOLAB",
      primaryColor: "#246b5b",
      accentColor: "#c27a2c",
      reportTitle: "SYSTOLAB Revenue Health Diagnosis",
      poweredByLabel: "Powered by SYSTOLAB Intelligence",
      footerLabel: "Powered by SYSTOLAB Intelligence"
    },
    scanCoverage: {
      sampledPages: 2,
      discoveredPages: 3,
      coverageLabel: "2 of 3 pages sampled",
      robotsTxtStatus: "allowed",
      pageRoles: {}
    },
    oss: {
      score: 72,
      scoringStatus: "scored",
      classification: "Action Recommended",
      visualState: visualStateForScore(72),
      explanation: "OSS is evidence-bound."
    },
    businessRiskStatus: {
      classification: "MEDIUM",
      level: "Medium Structural Risk",
      primaryRiskDriver: "Conversion readiness is the lowest validated area.",
      explanation: "Risk is based on observable website structure only.",
      evidenceIds: []
    },
    evidenceCoverageSummary: {
      totalPagesSampled: 2,
      totalEvidenceObjects: 12,
      pages: []
    },
    dimensions: [
      {
        key: "conversionReadiness",
        label: "Conversion Readiness",
        score: 58,
        classification: "Weak",
        visualState: visualStateForScore(58),
        businessMeaning: "Conversion readiness needs attention.",
        confidenceScore: 80,
        confidenceLevel: "High",
        evidenceIds: [],
        trace: []
      }
    ],
    decisionIntelligenceBrief: {
      executiveVerdict: {
        currentSituation: "The website is in an action recommended position.",
        seriousness: "Observable conversion readiness needs attention.",
        firstAction: "Clarify the primary call to action.",
        urgency: "This Month (7-30 days)",
        likelyBusinessImpact: "Structural opportunity estimate only.",
        evidenceBasis: "2 sampled pages and 12 validated evidence objects support this brief."
      },
      executiveActionBanner: {
        classification: "Action Recommended",
        message: "Improve the clearest validated conversion constraint first.",
        urgency: "This Month (7-30 days)"
      },
      executiveDecisionMatrix: {
        executiveDecisionScore: 72,
        riskLevel: "Medium Risk",
        executivePriority: "Improve",
        timeSensitivity: "This Month (7-30 days)",
        competitivePosition: "At Benchmark",
        primaryBusinessConstraint: "Conversion readiness is the lowest validated dimension.",
        potentialBusinessImpact: "Structural opportunity estimate only.",
        ifNotAddressedOutcome: "Visitors may not see the next step clearly.",
        recommendedNextAction: "Clarify the primary call to action."
      },
      actionPlan: [
        {
          priority: "Priority 1",
          action: "Clarify the primary call to action.",
          rationale: "The first action should reduce conversion friction.",
          confidenceScore: 80,
          confidenceLevel: "High",
          evidenceIds: []
        },
        {
          priority: "Priority 2",
          action: "Improve trust context around the action area.",
          rationale: "Trust context supports decision confidence.",
          confidenceScore: 75,
          confidenceLevel: "Moderate",
          evidenceIds: []
        },
        {
          priority: "Priority 3",
          action: "Re-run the assessment after changes.",
          rationale: "A follow-up scan validates improvement.",
          confidenceScore: 75,
          confidenceLevel: "Moderate",
          evidenceIds: []
        }
      ],
      whyThisMatters: {
        overallCondition: "The site has a usable structure with conversion gaps.",
        strongestValidatedDimensions: ["Website Health (82/100)"],
        weakestValidatedDimension: "Conversion Readiness (58/100)",
        businessSignificance: "The clearest action path should be easier to understand."
      },
      competitivePositionAnalysis: {
        summary: "Benchmark position is within range for available evidence.",
        benchmarkStatus: "At Benchmark",
        competitorStatus: "Competitor Data Unavailable",
        dimensionPositions: []
      },
      executiveReliabilityPanel: {
        evidenceCoverage: "2 sampled pages, 12 validated evidence objects.",
        crawlCoverage: "2 of 3 pages sampled",
        assessmentConfidence: "80% (High)",
        benchmarkConfidence: "72% (available)",
        assessmentTrustSignals: "3 trust evidence objects validated.",
        overallReportReliability: "High",
        limitations: ["Competitor position was not assessed."]
      }
    },
    recommendationEngine: {
      status: "generated",
      recommendations: [
        {
          recommendationId: "REC-001",
          issue: "CTA clarity",
          action: "Clarify the primary call to action.",
          priority: "THIS MONTH",
          mappedDimensions: ["conversionReadiness"],
          expectedScoreMovement: 5,
          revenueIntelligenceMapping: "Structural impact only.",
          confidenceScore: 80,
          evidenceIds: [],
          changeValidationPlan: "Re-scan after implementation."
        }
      ],
      mappingSystem: {
        rule: "one_recommendation_one_change_cluster",
        explanation: "One recommendation maps to one change cluster."
      }
    },
    recommendationOutcomeLoop: {
      status: "validated",
      previousSnapshotId: "snap_previous",
      validations: makeOutcomeValidations(9),
      summary: "Recommendation outcomes were validated where follow-up evidence existed."
    },
    priorityTimeline: {
      fixNow: [],
      thisMonth: [
        {
          actionId: "A1",
          action: "Clarify the primary call to action.",
          category: "THIS MONTH",
          timeWindow: "7-30 days",
          structuralSeverity: "Medium",
          evidenceStrength: "High",
          evidenceIds: []
        }
      ],
      monitor: []
    },
    confidenceEngine: {
      overallConfidenceScore: 80,
      confidenceLevel: "High",
      factors: [],
      estimateExplanations: []
    },
    confidenceLayer: [],
    evidenceObjects: [],
    evidenceDatabase: makeEvidenceDatabase(13),
    freshness: {
      capturedAt: "2026-06-15T06:00:00.000Z",
      cacheStatus: "live_capture",
      validityWindowHours: 72,
      stalenessRisk: "low",
      nextRecommendedScanAt: "2026-06-18T06:00:00.000Z"
    },
    ossInterpretation: {
      layer: "decision",
      score: 72,
      strictClassification: "structural_friction",
      label: "Structural Friction",
      range: "40-74",
      oneLineDiagnosis: "Conversion readiness should be improved.",
      meaning: "Structural friction means observable conversion friction exists.",
      visualState: visualStateForScore(72)
    },
    unifiedIssueCanvas: {
      status: "active",
      preSignalClassification: [],
      canonicalIssues: [],
      duplicateCollapseEngine: { rule: "semantic_causal_equivalence", rawIssueCount: 1, canonicalIssueCount: 1, collapsedDuplicateCount: 0 },
      actionUnificationLayer: { rule: "one_issue_one_authoritative_action", authoritativeActionCount: 1, removedDuplicateActionCount: 0 },
      postGenerationNormalization: { rule: "one_meaning_one_representation", normalized: true, removedResidualDuplicateCount: 0 },
      priorityHierarchy: ["1. Conversion-blocking issues"]
    },
    globalOutputContract: {
      schemaVersion: "systolab.output_contract.v1",
      status: "active",
      keyDecisionSummary: [{ canonicalIssueId: "CI-001", summary: "Customers may be ready to act but need a clearer next step.", priorityTier: "FIX NOW" }],
      rootCauseClusters: [{ canonicalIssueId: "CI-001", primaryCausalDriver: "The customer action path is not strongly supported.", rootCauseStatement: "Conversion Readiness: action path gap." }],
      revenueImpactAreas: [{ canonicalIssueId: "CI-001", impactArea: "Lead readiness", businessImpact: "Structural opportunity only.", confidenceScore: 72 }],
      confidenceScore: 72,
      evidenceBreakdown: [{ canonicalIssueId: "CI-001", validatedFindingCount: 3, evidenceCoverage: "partial" }],
      actionPlanMapping: [{ canonicalIssueId: "CI-001", actionReference: "REC-001", authoritativeAction: "Clarify the primary call to action.", priorityTier: "FIX NOW" }],
      nonRedundancyRules: ["Each canonical issue appears once."],
      limitations: ["Decision support only."]
    },
    revenueIntelligence: {
      status: "input_limited",
      confidenceScore: 0,
      confidenceBasis: "Not estimated in fixture.",
      trafficRange: estimate(),
      conversionPotentialRange: estimate(),
      revenueOpportunityRange: estimate(),
      opportunityCostRange: estimate(),
      competitorRevenuePressure: { status: "not_assessed", pressureLevel: "Unknown", explanation: "Not assessed.", evidenceIds: [] },
      limitations: []
    }
  } as unknown as ReportSnapshot;
}

function estimate() {
  return {
    label: "Not estimated",
    low: 0,
    high: 0,
    unit: "monthly_value_units",
    confidenceScore: 0,
    rationale: "Not estimated.",
    evidenceIds: []
  };
}

function makeEvidenceDatabase(count: number) {
  return Array.from({ length: count }, (_, index) => {
    const id = `EV-${String(index + 1).padStart(3, "0")}`;
    return {
      evidenceId: id,
      issue: `Evidence item ${index + 1}`,
      before: index % 2 === 0 ? null : "Previous state",
      after: "Validated state",
      confidenceScore: 80,
      confidenceReason: "Fixture confidence basis.",
      evidenceType: "issue_state",
      lineage: {
        snapshotId: "snap_pdf_enterprise",
        previousSnapshotId: "snap_previous",
        sourceEvidenceIds: [id],
        recommendationIds: ["REC-001"],
        validationTraceIds: []
      },
      capturedAt: "2026-06-15T06:00:00.000Z"
    };
  });
}

function makeOutcomeValidations(count: number) {
  return Array.from({ length: count }, (_, index) => ({
    recommendationId: `REC-${String(index + 1).padStart(3, "0")}`,
    recommendation: `Validate recommendation ${index + 1}`,
    implementedStatus: "validated",
    detectedAt: "2026-06-15T06:00:00.000Z",
    ossDelta: index + 1,
    dimensionDeltas: [],
    improvementStatus: "improved",
    revenueImpact: estimate(),
    confidenceScore: 82,
    confidenceReasons: ["Fixture validation basis."],
    evidenceIds: [`EV-${String(index + 1).padStart(3, "0")}`]
  }));
}
